/*
================================================================================
Project 4 — Talon Robotics: Payload Deployment Delivery
Script:  01_create_schema.sql
Purpose: Create the TalonDelivery database and its dimensional model.

BUSINESS QUESTION
    Is the new payload ready to ship, and what is still open?

THE SCHEMA DECISION THAT MAKES THE ANSWER POSSIBLE

    A verification is a DATED FACT AGAINST A BUILD, not an attribute of a
    requirement.

    The obvious model puts a Verified flag, or a VerifiedDate, on the
    requirement row. It is simpler, it is what most trackers actually do, and
    it makes the central question of this project impossible to ask. A test
    result is evidence about ONE BUILD. If REQ-0142 passed on build 12 and the
    flight-control subsystem changed in build 17, the flag still says Verified
    and is describing software that no longer exists.

    So Fact_TestRun carries both a TestCaseKey and a BuildKey, and
    Fact_BuildSubsystemChange records which subsystems each build touched.
    Staleness is then COMPUTABLE rather than asserted: a verification is
    current if nothing it depended on has moved since it ran.

    This is the same shape as Project 3's price agreements. A contracted price
    is true between two dates; a test result is true for one build. Storing
    either as an attribute lets today's answer silently govern yesterday's
    question.

TWO MORE DECISIONS WORTH THE COMMENT

    Requirements change, and the change is recorded. Fact_RequirementChange
    exists because a requirement that was reworded after it was verified is
    just as stale as one whose code moved -- the test may now be checking the
    wrong thing. Without this table, "verified" silently means "verified
    against some earlier version of the sentence".

    What COUNTS as verification is a reference table, not a CASE expression.
    Ref_VerificationPolicy states, per requirement type, which test level is
    sufficient evidence -- a safety requirement is not verified by a unit test.
    It is the single most contestable input in the analysis, so it lives where
    a systems engineer can see it, challenge it and change it, exactly as the
    erosion benchmark does in Project 3.

DATA DISCLOSURE
    Talon Robotics is a fictional mechatronics company. All data is synthetic
    and generated by 02_generate_synthetic_data.sql. No confidential data is
    used and no claim is made about any production system.
================================================================================
*/

USE master;
GO

IF DB_ID('TalonDelivery') IS NOT NULL
BEGIN
    ALTER DATABASE TalonDelivery SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE TalonDelivery;
END
GO
CREATE DATABASE TalonDelivery;
GO
USE TalonDelivery;
GO

-- =============================================================================
-- DIMENSIONS
-- =============================================================================

CREATE TABLE dbo.Dim_Date (
    DateKey      INT          NOT NULL PRIMARY KEY,   -- YYYYMMDD
    [Date]       DATE         NOT NULL UNIQUE,
    [Year]       SMALLINT     NOT NULL,
    [Quarter]    TINYINT      NOT NULL,
    [Month]      TINYINT      NOT NULL,
    MonthName    VARCHAR(12)  NOT NULL,
    YearMonth    CHAR(7)      NOT NULL,
    YearQuarter  CHAR(7)      NOT NULL,
    MonthEndDate DATE         NOT NULL,
    IsMonthEnd   BIT          NOT NULL,
    IsWeekend    BIT          NOT NULL,
    IsWorkday    BIT          NOT NULL
);
GO

CREATE TABLE dbo.Dim_Subsystem (
    SubsystemKey  INT IDENTITY(1,1) PRIMARY KEY,
    SubsystemCode VARCHAR(12)  NOT NULL UNIQUE,
    SubsystemName VARCHAR(60)  NOT NULL,
    -- Criticality drives which verification level the policy demands, and it
    -- drives the ship gate. A payload release cannot be held on a cosmetic
    -- defect in ground software, and cannot ship on an unverified release
    -- mechanism.
    Criticality   VARCHAR(12)  NOT NULL
        CHECK (Criticality IN ('Safety', 'Mission', 'Support')),
    -- Hardware-in-the-loop time is the scarce resource in this programme, so
    -- the queue has to know which subsystems compete for it.
    RequiresHILRig BIT         NOT NULL,
    LeadEngineerID VARCHAR(10) NOT NULL
);
GO

CREATE TABLE dbo.Dim_Person (
    PersonKey  INT IDENTITY(1,1) PRIMARY KEY,
    PersonID   VARCHAR(10)  NOT NULL UNIQUE,
    PersonName VARCHAR(60)  NOT NULL,
    [Role]     VARCHAR(24)  NOT NULL
        CHECK ([Role] IN ('Systems Engineer','Software Engineer','Test Engineer',
                          'Quality Engineer','Project Manager','Hardware Engineer')),
    Team       VARCHAR(30)  NOT NULL,
    -- Verification capacity per week, in test-hours. The priority queue is
    -- bounded by this: a list of everything outstanding is not a plan.
    WeeklyCapacityHours DECIMAL(5,1) NOT NULL
);
GO

CREATE TABLE dbo.Dim_Build (
    BuildKey        INT IDENTITY(1,1) PRIMARY KEY,
    BuildID         VARCHAR(12) NOT NULL UNIQUE,     -- e.g. B-0042
    BuildNumber     INT         NOT NULL UNIQUE,     -- monotonic; ordering is by this, never by date
    BuildDateKey    INT         NOT NULL,
    BuildLabel      VARCHAR(40) NOT NULL,
    -- A release candidate is the thing being shipped. Readiness is always
    -- computed against ONE specific build, never "the latest of everything".
    IsReleaseCandidate BIT      NOT NULL,
    CONSTRAINT FK_Build_Date FOREIGN KEY (BuildDateKey) REFERENCES dbo.Dim_Date(DateKey)
);
GO

CREATE TABLE dbo.Dim_Requirement (
    RequirementKey  INT IDENTITY(1,1) PRIMARY KEY,
    RequirementID   VARCHAR(12) NOT NULL UNIQUE,     -- e.g. REQ-0142
    Title           VARCHAR(160) NOT NULL,
    ReqType         VARCHAR(16) NOT NULL
        CHECK (ReqType IN ('Functional','Performance','Safety','Interface','Regulatory')),
    -- The ship gate is computed over MustShip only. A readiness percentage
    -- that mixes must-ship and nice-to-have is arithmetic without a decision
    -- attached: it cannot tell you whether to ship.
    Priority        VARCHAR(12) NOT NULL
        CHECK (Priority IN ('MustShip','ShouldShip','Nice')),
    SubsystemKey    INT         NOT NULL,
    OwnerKey        INT         NOT NULL,
    BaselinedDateKey INT        NOT NULL,
    -- Requirements can be withdrawn. A withdrawn requirement is not a failure
    -- to verify, and counting it as one understates readiness.
    ReqStatus       VARCHAR(12) NOT NULL
        CHECK (ReqStatus IN ('Baselined','Withdrawn')),
    CONSTRAINT FK_Req_Subsystem FOREIGN KEY (SubsystemKey)    REFERENCES dbo.Dim_Subsystem(SubsystemKey),
    CONSTRAINT FK_Req_Owner     FOREIGN KEY (OwnerKey)        REFERENCES dbo.Dim_Person(PersonKey),
    CONSTRAINT FK_Req_Date      FOREIGN KEY (BaselinedDateKey) REFERENCES dbo.Dim_Date(DateKey)
);
GO

CREATE TABLE dbo.Dim_TestCase (
    TestCaseKey    INT IDENTITY(1,1) PRIMARY KEY,
    TestCaseID     VARCHAR(12) NOT NULL UNIQUE,      -- e.g. TC-0318
    RequirementKey INT         NOT NULL,
    -- Test level is the evidence grade. Ref_VerificationPolicy decides which
    -- grade is sufficient for which requirement type; this column only records
    -- what the test actually is.
    TestLevel      VARCHAR(16) NOT NULL
        CHECK (TestLevel IN ('Unit','Integration','HIL','Field')),
    AutomationLevel VARCHAR(12) NOT NULL
        CHECK (AutomationLevel IN ('Automated','Manual')),
    ExpectedDurationMin INT    NOT NULL,
    CONSTRAINT FK_TC_Req FOREIGN KEY (RequirementKey) REFERENCES dbo.Dim_Requirement(RequirementKey)
);
GO

-- =============================================================================
-- FACTS
-- =============================================================================

/*
Fact_TestRun -- the evidence. One row per execution of one test case against
one build.

BuildKey is the point of the whole model. A result without a build is an
opinion: it tells you something passed once, not whether it passes on the
thing you are about to ship.
*/
CREATE TABLE dbo.Fact_TestRun (
    TestRunKey   INT IDENTITY(1,1) PRIMARY KEY,
    TestCaseKey  INT         NOT NULL,
    BuildKey     INT         NOT NULL,
    RunDateKey   INT         NOT NULL,
    RunByKey     INT         NOT NULL,
    Result       VARCHAR(10) NOT NULL
        CHECK (Result IN ('Pass','Fail','Blocked')),
    DurationMin  INT         NOT NULL,
    CONSTRAINT FK_Run_TC    FOREIGN KEY (TestCaseKey) REFERENCES dbo.Dim_TestCase(TestCaseKey),
    CONSTRAINT FK_Run_Build FOREIGN KEY (BuildKey)    REFERENCES dbo.Dim_Build(BuildKey),
    CONSTRAINT FK_Run_Date  FOREIGN KEY (RunDateKey)  REFERENCES dbo.Dim_Date(DateKey),
    CONSTRAINT FK_Run_By    FOREIGN KEY (RunByKey)    REFERENCES dbo.Dim_Person(PersonKey)
);
GO
CREATE INDEX IX_TestRun_Case_Build ON dbo.Fact_TestRun (TestCaseKey, BuildKey) INCLUDE (Result, RunDateKey);
GO

/*
Fact_BuildSubsystemChange -- what each build actually touched.

Without this, staleness cannot be distinguished from age. A verification from
six months ago is perfectly good if nothing underneath it has moved; a
verification from last week is worthless if the subsystem was rewritten on
Monday. Elapsed time is not the question -- intervening change is.
*/
CREATE TABLE dbo.Fact_BuildSubsystemChange (
    BuildKey     INT NOT NULL,
    SubsystemKey INT NOT NULL,
    -- Lines changed is a proxy for "how much moved". It is deliberately not
    -- used as a threshold: any change at all invalidates a verification. It is
    -- carried so a reviewer can see the size of what invalidated it.
    LinesChanged INT NOT NULL,
    CONSTRAINT PK_BuildSubsystemChange PRIMARY KEY (BuildKey, SubsystemKey),
    CONSTRAINT FK_BSC_Build     FOREIGN KEY (BuildKey)     REFERENCES dbo.Dim_Build(BuildKey),
    CONSTRAINT FK_BSC_Subsystem FOREIGN KEY (SubsystemKey) REFERENCES dbo.Dim_Subsystem(SubsystemKey)
);
GO

/*
Fact_RequirementChange -- when the requirement itself moved.

A requirement reworded after it was verified is as stale as one whose code
changed: the test may now be checking the wrong sentence. Clarifications are
recorded separately from modifications because only one of them invalidates
evidence, and conflating them would either overstate staleness or hide it.
*/
CREATE TABLE dbo.Fact_RequirementChange (
    RequirementChangeKey INT IDENTITY(1,1) PRIMARY KEY,
    RequirementKey INT         NOT NULL,
    ChangeDateKey  INT         NOT NULL,
    BuildKey       INT         NOT NULL,   -- the build current when the change landed
    ChangeType     VARCHAR(14) NOT NULL
        CHECK (ChangeType IN ('Modified','Clarified')),
    ChangedByKey   INT         NOT NULL,
    ChangeNote     VARCHAR(200) NOT NULL,
    CONSTRAINT FK_RC_Req   FOREIGN KEY (RequirementKey) REFERENCES dbo.Dim_Requirement(RequirementKey),
    CONSTRAINT FK_RC_Date  FOREIGN KEY (ChangeDateKey)  REFERENCES dbo.Dim_Date(DateKey),
    CONSTRAINT FK_RC_Build FOREIGN KEY (BuildKey)       REFERENCES dbo.Dim_Build(BuildKey),
    CONSTRAINT FK_RC_By    FOREIGN KEY (ChangedByKey)   REFERENCES dbo.Dim_Person(PersonKey)
);
GO

/*
Fact_WorkItem -- the flattering number.

This is where "94% complete" comes from: closed work items over total work
items. It is a real metric that real programmes report, and it is not a lie.
It is simply not an answer to "can we ship", because it counts effort rather
than evidence. It is modelled so the two can be put side by side.
*/
CREATE TABLE dbo.Fact_WorkItem (
    WorkItemKey    INT IDENTITY(1,1) PRIMARY KEY,
    WorkItemID     VARCHAR(12) NOT NULL UNIQUE,
    RequirementKey INT         NOT NULL,
    AssignedToKey  INT         NOT NULL,
    OpenedDateKey  INT         NOT NULL,
    ClosedDateKey  INT         NULL,
    EstimateHours  DECIMAL(6,1) NOT NULL,
    ActualHours    DECIMAL(6,1) NULL,
    WorkItemStatus VARCHAR(12) NOT NULL
        CHECK (WorkItemStatus IN ('Open','InProgress','Closed')),
    CONSTRAINT FK_WI_Req    FOREIGN KEY (RequirementKey) REFERENCES dbo.Dim_Requirement(RequirementKey),
    CONSTRAINT FK_WI_Person FOREIGN KEY (AssignedToKey)  REFERENCES dbo.Dim_Person(PersonKey),
    CONSTRAINT FK_WI_Opened FOREIGN KEY (OpenedDateKey)  REFERENCES dbo.Dim_Date(DateKey),
    CONSTRAINT FK_WI_Closed FOREIGN KEY (ClosedDateKey)  REFERENCES dbo.Dim_Date(DateKey)
);
GO

/*
Fact_RAID -- Risks, Assumptions, Issues, Dependencies.

Exposure is probability x impact, both read from Ref_RAIDMatrix rather than
hardcoded, so a programme board can re-score the matrix without a code change.

ClosedDateKey is nullable and OwnerKey is NOT nullable on purpose: an
unowned risk is the most common way a RAID log becomes decorative, so the
schema makes it impossible to raise one without an owner, and the data-quality
layer then looks for owners who have left or are overloaded instead.
*/
CREATE TABLE dbo.Fact_RAID (
    RAIDKey       INT IDENTITY(1,1) PRIMARY KEY,
    RAIDID        VARCHAR(12) NOT NULL UNIQUE,
    RAIDType      VARCHAR(12) NOT NULL
        CHECK (RAIDType IN ('Risk','Assumption','Issue','Dependency')),
    Title         VARCHAR(160) NOT NULL,
    SubsystemKey  INT         NOT NULL,
    OwnerKey      INT         NOT NULL,
    RaisedDateKey INT         NOT NULL,
    DueDateKey    INT         NULL,
    ClosedDateKey INT         NULL,
    Probability   TINYINT     NOT NULL CHECK (Probability BETWEEN 1 AND 5),
    Impact        TINYINT     NOT NULL CHECK (Impact      BETWEEN 1 AND 5),
    RAIDStatus    VARCHAR(12) NOT NULL
        CHECK (RAIDStatus IN ('Open','Mitigating','Closed')),
    MitigationNote VARCHAR(250) NOT NULL,
    CONSTRAINT FK_RAID_Subsystem FOREIGN KEY (SubsystemKey)  REFERENCES dbo.Dim_Subsystem(SubsystemKey),
    CONSTRAINT FK_RAID_Owner     FOREIGN KEY (OwnerKey)      REFERENCES dbo.Dim_Person(PersonKey),
    CONSTRAINT FK_RAID_Raised    FOREIGN KEY (RaisedDateKey) REFERENCES dbo.Dim_Date(DateKey),
    CONSTRAINT FK_RAID_Due       FOREIGN KEY (DueDateKey)    REFERENCES dbo.Dim_Date(DateKey),
    CONSTRAINT FK_RAID_Closed    FOREIGN KEY (ClosedDateKey) REFERENCES dbo.Dim_Date(DateKey)
);
GO

-- =============================================================================
-- REFERENCE TABLES
-- The contestable inputs. Each lives here rather than inside a query so that
-- the person who disagrees with it can find it, argue with it and change it.
-- =============================================================================

/*
Ref_VerificationPolicy -- what counts as evidence.

The single most contestable input in this project. A safety requirement is not
verified by a unit test, and saying so in a CASE expression buried in a view
means the rule is invisible to the systems engineer whose judgement it encodes.

MinTestLevel is ordered: Unit < Integration < HIL < Field. A test at or above
the minimum grade is sufficient evidence.
*/
CREATE TABLE dbo.Ref_VerificationPolicy (
    ReqType          VARCHAR(16) NOT NULL PRIMARY KEY,
    MinTestLevel     VARCHAR(16) NOT NULL
        CHECK (MinTestLevel IN ('Unit','Integration','HIL','Field')),
    MinTestLevelRank TINYINT     NOT NULL,   -- 1..4, so SQL can compare grades
    RequiresIndependentTester BIT NOT NULL,  -- the author may not verify their own work
    PolicyNote       VARCHAR(220) NOT NULL
);
GO

CREATE TABLE dbo.Ref_TestLevelRank (
    TestLevel     VARCHAR(16) NOT NULL PRIMARY KEY,
    LevelRank     TINYINT     NOT NULL UNIQUE,
    RigHours      DECIMAL(5,2) NOT NULL,     -- scarce-resource cost of one run
    LevelNote     VARCHAR(160) NOT NULL
);
GO

CREATE TABLE dbo.Ref_RAIDMatrix (
    Probability   TINYINT     NOT NULL,
    Impact        TINYINT     NOT NULL,
    ExposureScore TINYINT     NOT NULL,
    ExposureBand  VARCHAR(10) NOT NULL
        CHECK (ExposureBand IN ('Low','Medium','High','Critical')),
    CONSTRAINT PK_RAIDMatrix PRIMARY KEY (Probability, Impact)
);
GO

CREATE TABLE dbo.Ref_ReadinessTargets (
    MetricName    VARCHAR(40)   NOT NULL PRIMARY KEY,
    TargetValue   DECIMAL(10,2) NOT NULL,
    WarningValue  DECIMAL(10,2) NOT NULL,
    Direction     VARCHAR(15)   NOT NULL CHECK (Direction IN ('HigherBetter','LowerBetter')),
    Unit          VARCHAR(10)   NOT NULL CHECK (Unit IN ('Percent','Count','Hours','Score')),
    [Description] VARCHAR(220)  NOT NULL
);
GO

-- =============================================================================
-- REFERENCE DATA
-- =============================================================================

INSERT INTO dbo.Ref_TestLevelRank (TestLevel, LevelRank, RigHours, LevelNote) VALUES
 ('Unit',        1, 0.00, 'Runs on a developer machine against mocked interfaces. Proves the code does what its author meant.'),
 ('Integration', 2, 0.00, 'Runs the real subsystem against real neighbours in software. Proves the interfaces agree.'),
 ('HIL',         3, 2.50, 'Hardware in the loop on the payload rig. Proves the software drives the actual mechanism.'),
 ('Field',       4, 8.00, 'Flown on the airframe. The only evidence that survives contact with the environment.');
GO

INSERT INTO dbo.Ref_VerificationPolicy (ReqType, MinTestLevel, MinTestLevelRank, RequiresIndependentTester, PolicyNote) VALUES
 ('Functional',  'Integration', 2, 0,
  'Interfaces must be exercised against real neighbours. A unit test proves the author''s intent, not the behaviour.'),
 ('Performance', 'HIL',         3, 0,
  'Timing and power figures measured in software are estimates. Performance is verified on the rig or not at all.'),
 ('Safety',      'HIL',         3, 1,
  'Safety requirements are verified on hardware and by someone other than the author. Both halves are the rule; either alone has failed before.'),
 ('Interface',   'Integration', 2, 0,
  'An interface is verified when both sides run together. A mock agrees with whatever it was written to agree with.'),
 ('Regulatory',  'Field',       4, 1,
  'Certification evidence must come from the airframe, independently witnessed. Rig data is not accepted by the authority.');
GO

-- Exposure = Probability x Impact, banded. Written out in full rather than
-- computed, because a programme board routinely wants to distort the corners
-- (a 1x5 "unlikely but catastrophic" is not treated as a 5x1 "certain but
-- trivial", though the product is identical), and a formula cannot express that.
INSERT INTO dbo.Ref_RAIDMatrix (Probability, Impact, ExposureScore, ExposureBand) VALUES
 (1,1,1,'Low'),    (1,2,2,'Low'),    (1,3,3,'Low'),     (1,4,8,'Medium'),  (1,5,10,'High'),
 (2,1,2,'Low'),    (2,2,4,'Low'),    (2,3,6,'Medium'),  (2,4,10,'Medium'), (2,5,15,'High'),
 (3,1,3,'Low'),    (3,2,6,'Medium'), (3,3,9,'Medium'),  (3,4,14,'High'),   (3,5,20,'Critical'),
 (4,1,4,'Low'),    (4,2,8,'Medium'), (4,3,14,'High'),   (4,4,18,'High'),   (4,5,24,'Critical'),
 (5,1,5,'Medium'), (5,2,10,'Medium'),(5,3,17,'High'),   (5,4,22,'Critical'),(5,5,25,'Critical');
GO

INSERT INTO dbo.Ref_ReadinessTargets (MetricName, TargetValue, WarningValue, Direction, Unit, [Description]) VALUES
 ('ShipReadinessPct',        100.00, 95.00, 'HigherBetter', 'Percent',
  'MustShip requirements whose latest passing verification is still CURRENT and meets policy. The ship gate; 100% is the only passing value, because a must-ship requirement is by definition one you cannot ship without.'),
 ('VerificationCoveragePct',  95.00, 85.00, 'HigherBetter', 'Percent',
  'Baselined requirements with any passing verification on any build. Says evidence exists; says nothing about whether it still applies.'),
 ('StaleVerificationPct',     15.00, 30.00, 'LowerBetter',  'Percent',
  'Of requirements that have evidence, the share whose latest passing run predates a change to the same subsystem or a Modified change to the requirement itself. The gap between coverage and readiness.'),
 ('WorkItemCompletionPct',    95.00, 85.00, 'HigherBetter', 'Percent',
  'Closed work items over all work items. Reported because the programme reports it; it counts effort, not evidence.'),
 ('PolicyCompliancePct',      100.00, 95.00,'HigherBetter', 'Percent',
  'Verifications meeting Ref_VerificationPolicy for their requirement type, including the independent-tester rule.'),
 ('CriticalRAIDOpen',          0.00,  2.00, 'LowerBetter',  'Count',
  'Open or mitigating RAID items in the Critical exposure band.'),
 ('OverdueRAIDPct',           10.00, 25.00, 'LowerBetter',  'Percent',
  'Open RAID items past their due date, as a share of all open items.'),
 ('BlockedTestPct',            5.00, 12.00, 'LowerBetter',  'Percent',
  'Test cases whose most recent run against the release candidate was Blocked rather than Pass or Fail.');
GO

-- =============================================================================
-- Creation gate. Fail loudly rather than leave a half-built schema that the
-- next script will fail against in a more confusing way.
-- =============================================================================
DECLARE @missing VARCHAR(500) = '';
IF OBJECT_ID('dbo.Dim_Date','U')                  IS NULL SET @missing += 'Dim_Date ';
IF OBJECT_ID('dbo.Dim_Subsystem','U')             IS NULL SET @missing += 'Dim_Subsystem ';
IF OBJECT_ID('dbo.Dim_Person','U')                IS NULL SET @missing += 'Dim_Person ';
IF OBJECT_ID('dbo.Dim_Build','U')                 IS NULL SET @missing += 'Dim_Build ';
IF OBJECT_ID('dbo.Dim_Requirement','U')           IS NULL SET @missing += 'Dim_Requirement ';
IF OBJECT_ID('dbo.Dim_TestCase','U')              IS NULL SET @missing += 'Dim_TestCase ';
IF OBJECT_ID('dbo.Fact_TestRun','U')              IS NULL SET @missing += 'Fact_TestRun ';
IF OBJECT_ID('dbo.Fact_BuildSubsystemChange','U') IS NULL SET @missing += 'Fact_BuildSubsystemChange ';
IF OBJECT_ID('dbo.Fact_RequirementChange','U')    IS NULL SET @missing += 'Fact_RequirementChange ';
IF OBJECT_ID('dbo.Fact_WorkItem','U')             IS NULL SET @missing += 'Fact_WorkItem ';
IF OBJECT_ID('dbo.Fact_RAID','U')                 IS NULL SET @missing += 'Fact_RAID ';
IF OBJECT_ID('dbo.Ref_VerificationPolicy','U')    IS NULL SET @missing += 'Ref_VerificationPolicy ';
IF OBJECT_ID('dbo.Ref_TestLevelRank','U')         IS NULL SET @missing += 'Ref_TestLevelRank ';
IF OBJECT_ID('dbo.Ref_RAIDMatrix','U')            IS NULL SET @missing += 'Ref_RAIDMatrix ';
IF OBJECT_ID('dbo.Ref_ReadinessTargets','U')      IS NULL SET @missing += 'Ref_ReadinessTargets ';
IF @missing <> '' THROW 52001, 'FAILED to create the schema -- scroll up for the error.', 1;

IF (SELECT COUNT(*) FROM dbo.Ref_RAIDMatrix) <> 25
    THROW 52002, 'Ref_RAIDMatrix must hold all 25 probability/impact combinations.', 1;
IF (SELECT COUNT(*) FROM dbo.Ref_VerificationPolicy) <> 5
    THROW 52003, 'Ref_VerificationPolicy must cover every requirement type.', 1;

PRINT 'Schema created and verified: 6 dimensions, 5 facts, 4 reference tables.';
GO
