/*
================================================================================
Project 5 — Meridian UAV Services: Predictive Maintenance
Script:  01_create_schema.sql
Purpose: Create the MeridianUAV database and its dimensional model.

BUSINESS QUESTION
    Which airframes need maintenance before their next mission?

THE SCHEMA DECISION THAT MAKES THE ANSWER POSSIBLE

    Wear is measured in STRESS-WEIGHTED DUTY CYCLES, not flight hours.

    The obvious model tracks hours flown and compares them with a service
    interval expressed in hours. Every maintenance system in the world does
    this, it is simple, and it is measuring the wrong thing: an hour of coastal
    survey in still air at 12kg payload does not wear a rotor the way an hour
    of mountain thermal work at 28kg does. Same hour on the meter, several
    times the damage.

    So Fact_Sortie carries the mission profile, the payload, the ambient
    conditions and the landing count, and Ref_StressModel converts those into a
    damage multiplier per flight hour. Wear becomes COMPUTABLE from what the
    aircraft actually did, rather than assumed from how long it was airborne.

    The consequence is the finding: a fleet that is fully compliant on the hour
    meter is not compliant on the thing the hour meter is standing in for.

TWO MORE DECISIONS WORTH THE COMMENT

    A component instance is tracked, not a component type. Fact_ComponentInstall
    follows one physical part onto an airframe and off again, so a rotor
    replaced at 200 hours starts its own life at zero. Tracking wear at
    airframe level would age a new part by its aircraft's history, and no
    maintenance decision made on that basis is sound.

    The stress model is a reference table with a SourceNote on every row. It is
    the most contestable input in the analysis -- a maintenance engineer will
    want to argue about whether mountain work is really 2.4x coastal -- so it
    lives where that argument can happen, not inside a CASE expression.

DATA DISCLOSURE
    Meridian UAV Services is a fictional operator. All data is synthetic and
    generated by 02_generate_synthetic_data.sql. The degradation patterns are
    modelled on publicly described behaviour of rotating machinery (bearing
    spectral signatures, brushless motor current signatures, Weibull wear-out);
    no proprietary reliability data is used and no claim is made about any real
    aircraft, operator or manufacturer.
================================================================================
*/

USE master;
GO

IF DB_ID('MeridianUAV') IS NOT NULL
BEGIN
    ALTER DATABASE MeridianUAV SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE MeridianUAV;
END
GO
CREATE DATABASE MeridianUAV;
GO
USE MeridianUAV;
GO

-- =============================================================================
-- DIMENSIONS
-- =============================================================================

CREATE TABLE dbo.Dim_Date (
    DateKey      INT          NOT NULL PRIMARY KEY,   -- YYYYMMDD
    [Date]       DATE         NOT NULL UNIQUE,
    [Year]       SMALLINT     NOT NULL,
    [Quarter]    TINYINT      NOT NULL,
    [Month]      TINYINT      NOT NULL,
    MonthName    VARCHAR(12)  NOT NULL,
    YearMonth    CHAR(7)      NOT NULL,
    YearQuarter  CHAR(7)      NOT NULL,
    MonthEndDate DATE         NOT NULL,
    IsMonthEnd   BIT          NOT NULL,
    IsWeekend    BIT          NOT NULL
);
GO

CREATE TABLE dbo.Dim_Base (
    BaseKey    INT IDENTITY(1,1) PRIMARY KEY,
    BaseCode   VARCHAR(8)   NOT NULL UNIQUE,
    BaseName   VARCHAR(50)  NOT NULL,
    Region     VARCHAR(30)  NOT NULL,
    -- Hangar slots are the scarce resource. A maintenance queue that ignores
    -- them is a wish list: you cannot service eleven airframes in a week with
    -- three bays whatever the risk score says.
    HangarBays TINYINT      NOT NULL
);
GO

CREATE TABLE dbo.Dim_Airframe (
    AirframeKey     INT IDENTITY(1,1) PRIMARY KEY,
    TailNumber      VARCHAR(10)  NOT NULL UNIQUE,   -- e.g. MU-014
    ModelCode       VARCHAR(12)  NOT NULL,
    BaseKey         INT          NOT NULL,
    InServiceDateKey INT         NOT NULL,
    -- Airframes retired mid-window are not failures to maintain, and counting
    -- them as unserviced would overstate the backlog.
    AirframeStatus  VARCHAR(12)  NOT NULL
        CHECK (AirframeStatus IN ('Active','Retired')),
    RetiredDateKey  INT          NULL,
    CONSTRAINT FK_Airframe_Base FOREIGN KEY (BaseKey)          REFERENCES dbo.Dim_Base(BaseKey),
    CONSTRAINT FK_Airframe_InSvc FOREIGN KEY (InServiceDateKey) REFERENCES dbo.Dim_Date(DateKey),
    CONSTRAINT FK_Airframe_Retired FOREIGN KEY (RetiredDateKey) REFERENCES dbo.Dim_Date(DateKey)
);
GO

CREATE TABLE dbo.Dim_ComponentType (
    ComponentTypeKey INT IDENTITY(1,1) PRIMARY KEY,
    ComponentCode    VARCHAR(12)  NOT NULL UNIQUE,
    ComponentName    VARCHAR(50)  NOT NULL,
    -- How many of this component each airframe carries. Four rotor assemblies,
    -- one battery pack, and so on -- so a fleet count is not a component count.
    PositionsPerAirframe TINYINT  NOT NULL,
    -- Criticality drives whether a failure grounds the aircraft or degrades it.
    Criticality      VARCHAR(16)  NOT NULL
        CHECK (Criticality IN ('FlightCritical','MissionCritical','Degraded')),
    -- Lead time to obtain and fit. A prediction that arrives inside this window
    -- is not actionable, and that distinction is the second finding of this
    -- project.
    LeadTimeFlightHours DECIMAL(6,1) NOT NULL
);
GO

CREATE TABLE dbo.Dim_MissionProfile (
    MissionProfileKey INT IDENTITY(1,1) PRIMARY KEY,
    ProfileCode       VARCHAR(12)  NOT NULL UNIQUE,
    ProfileName       VARCHAR(50)  NOT NULL,
    TypicalPayloadKg  DECIMAL(5,1) NOT NULL,
    [Description]     VARCHAR(200) NOT NULL
);
GO

-- =============================================================================
-- FACTS
-- =============================================================================

/*
Fact_Sortie -- one row per flight.

Carries what the aircraft actually DID, not merely how long it was up. Every
column here except duration exists because it changes how much damage the hour
does, and the stress model reads them.
*/
CREATE TABLE dbo.Fact_Sortie (
    SortieKey        INT IDENTITY(1,1) PRIMARY KEY,
    SortieID         VARCHAR(14) NOT NULL UNIQUE,
    AirframeKey      INT         NOT NULL,
    MissionProfileKey INT        NOT NULL,
    SortieDateKey    INT         NOT NULL,
    FlightMinutes    INT         NOT NULL,
    PayloadKg        DECIMAL(5,1) NOT NULL,
    -- Landings are a cycle count: take-off and landing load the airframe far
    -- more than cruise, so six short sorties are not one long one.
    Landings         TINYINT     NOT NULL,
    AmbientTempC     DECIMAL(4,1) NOT NULL,
    WindGustKts      DECIMAL(4,1) NOT NULL,
    CONSTRAINT FK_Sortie_Airframe FOREIGN KEY (AirframeKey)       REFERENCES dbo.Dim_Airframe(AirframeKey),
    CONSTRAINT FK_Sortie_Profile  FOREIGN KEY (MissionProfileKey) REFERENCES dbo.Dim_MissionProfile(MissionProfileKey),
    CONSTRAINT FK_Sortie_Date     FOREIGN KEY (SortieDateKey)     REFERENCES dbo.Dim_Date(DateKey)
);
GO
CREATE INDEX IX_Sortie_Airframe_Date ON dbo.Fact_Sortie (AirframeKey, SortieDateKey) INCLUDE (FlightMinutes, Landings, PayloadKg);
GO

/*
Fact_ComponentInstall -- one physical part, on one airframe, in one position.

The grain that makes remaining-life meaningful. A rotor fitted at the airframe's
400th hour starts its own life at zero; ageing it by the aircraft's history
would condemn a new part and clear a worn one.

RemovedDateKey NULL means still fitted.
*/
CREATE TABLE dbo.Fact_ComponentInstall (
    InstallKey        INT IDENTITY(1,1) PRIMARY KEY,
    ComponentSerial   VARCHAR(18) NOT NULL UNIQUE,
    ComponentTypeKey  INT         NOT NULL,
    AirframeKey       INT         NOT NULL,
    PositionNo        TINYINT     NOT NULL,
    InstalledDateKey  INT         NOT NULL,
    RemovedDateKey    INT         NULL,
    RemovalReason     VARCHAR(20) NULL
        CHECK (RemovalReason IN ('Scheduled','Failure','Precautionary','AirframeRetired')),
    CONSTRAINT FK_Install_Type     FOREIGN KEY (ComponentTypeKey) REFERENCES dbo.Dim_ComponentType(ComponentTypeKey),
    CONSTRAINT FK_Install_Airframe FOREIGN KEY (AirframeKey)      REFERENCES dbo.Dim_Airframe(AirframeKey),
    CONSTRAINT FK_Install_In       FOREIGN KEY (InstalledDateKey) REFERENCES dbo.Dim_Date(DateKey),
    CONSTRAINT FK_Install_Out      FOREIGN KEY (RemovedDateKey)   REFERENCES dbo.Dim_Date(DateKey)
);
GO
CREATE INDEX IX_Install_Airframe ON dbo.Fact_ComponentInstall (AirframeKey, ComponentTypeKey) INCLUDE (InstalledDateKey, RemovedDateKey);
GO

/*
Fact_MaintenanceEvent -- what was actually done, and why.

Scheduled and unscheduled are recorded in the same table with an EventType,
because the ratio between them is itself a KPI: a fleet doing mostly
unscheduled work is being maintained by its failures.
*/
CREATE TABLE dbo.Fact_MaintenanceEvent (
    EventKey        INT IDENTITY(1,1) PRIMARY KEY,
    EventID         VARCHAR(14) NOT NULL UNIQUE,
    AirframeKey     INT         NOT NULL,
    InstallKey      INT         NULL,        -- NULL = airframe-level work
    EventDateKey    INT         NOT NULL,
    EventType       VARCHAR(16) NOT NULL
        CHECK (EventType IN ('Scheduled','Unscheduled','Inspection')),
    -- Hours ON THE COMPONENT at the event, not on the airframe.
    ComponentHoursAtEvent DECIMAL(9,2) NULL,
    DowntimeHours   DECIMAL(6,1) NOT NULL,
    Finding         VARCHAR(200) NOT NULL,
    CONSTRAINT FK_Event_Airframe FOREIGN KEY (AirframeKey)  REFERENCES dbo.Dim_Airframe(AirframeKey),
    CONSTRAINT FK_Event_Install  FOREIGN KEY (InstallKey)   REFERENCES dbo.Fact_ComponentInstall(InstallKey),
    CONSTRAINT FK_Event_Date     FOREIGN KEY (EventDateKey) REFERENCES dbo.Dim_Date(DateKey)
);
GO

/*
Fact_SensorReading -- post-sortie condition monitoring, one row per component
instance per sortie.

Deliberately at SORTIE grain rather than raw telemetry: the downloaded summary
is what an operator of this size actually keeps, and a model trained on what
exists is worth more than one trained on data nobody has.
*/
CREATE TABLE dbo.Fact_SensorReading (
    ReadingKey      INT IDENTITY(1,1) PRIMARY KEY,
    SortieKey       INT          NOT NULL,
    InstallKey      INT          NOT NULL,
    -- RMS vibration in the bearing band. The classic wear-out signal, and the
    -- one that rises earliest.
    VibrationRms    DECIMAL(7,4) NOT NULL,
    -- Peak winding temperature above ambient, so the measure is comparable
    -- between a January sortie and an August one.
    TempRiseC       DECIMAL(5,2) NOT NULL,
    -- Current drawn for the same commanded thrust: rises as bearings stiffen.
    CurrentDrawA    DECIMAL(6,3) NOT NULL,
    CONSTRAINT FK_Reading_Sortie  FOREIGN KEY (SortieKey)  REFERENCES dbo.Fact_Sortie(SortieKey),
    CONSTRAINT FK_Reading_Install FOREIGN KEY (InstallKey) REFERENCES dbo.Fact_ComponentInstall(InstallKey)
);
GO
CREATE INDEX IX_Reading_Install ON dbo.Fact_SensorReading (InstallKey, SortieKey) INCLUDE (VibrationRms, TempRiseC, CurrentDrawA);
GO

-- =============================================================================
-- REFERENCE TABLES
-- The contestable inputs. Each lives here rather than inside a query so that
-- the engineer who disagrees can find it, argue with it and change it.
-- =============================================================================

/*
Ref_StressModel -- the damage multiplier per flight hour, by mission profile.

The single most contestable input in this project. A maintenance engineer will
want to argue about whether mountain work really costs 2.4 times coastal, and
that argument is the right one to be having -- so the number sits in a table
with its reasoning attached rather than buried in a CASE expression where
nobody can see it to disagree.
*/
/*
WHAT THIS TABLE DELIBERATELY DOES NOT REPRESENT

It is keyed on the mission profile alone. There is no component dimension, so a
landing costs a rotor assembly exactly what it costs the landing gear.

Physically that is wrong, and it is stated here rather than left for a reader to
discover. Modelling per-component damage coefficients would need six times the
reference data and a source for each cell, and this project has no such source.
What the model does support is the comparison it was built for: two airframes
flying different work accrue different damage per logged hour. That conclusion
does not depend on the missing dimension.

The consequence to be aware of when reading results by component: differences in
unscheduled rate BETWEEN component types come from their Weibull shapes and
intervals, not from any component-specific response to landings.
*/
CREATE TABLE dbo.Ref_StressModel (
    ProfileCode       VARCHAR(12)  NOT NULL PRIMARY KEY,
    StressMultiplier  DECIMAL(5,3) NOT NULL,
    -- Additional damage per landing, expressed in equivalent flight hours.
    CyclePenaltyHours DECIMAL(5,3) NOT NULL,
    -- Additional damage per kg of payload above the nominal 12kg, per hour.
    PayloadPenaltyPerKg DECIMAL(6,4) NOT NULL,
    -- 400, not 220. These notes carry the ARGUMENT for a coefficient that moves
    -- every figure in the project, and a column too narrow to hold the argument
    -- is a column that quietly encourages leaving it out. Third truncation of
    -- this kind in this portfolio; the pattern is always the same -- the
    -- reasoning outgrows a width chosen before the reasoning existed.
    SourceNote        VARCHAR(400) NOT NULL
);
GO

/*
Ref_ServiceInterval -- the interval, expressed BOTH ways.

Both columns exist so the two can be compared, which is the whole point. The
hour interval is what the maintenance system enforces today; the cycle interval
is what the manufacturer's data actually supports once stress is accounted for.
*/
CREATE TABLE dbo.Ref_ServiceInterval (
    ComponentCode          VARCHAR(12)  NOT NULL PRIMARY KEY,
    IntervalFlightHours    DECIMAL(7,1) NOT NULL,
    IntervalStressHours    DECIMAL(7,1) NOT NULL,
    -- Weibull shape. Above 1 means wear-out: failure rate RISES with age, and
    -- the mean time between failures is the wrong statistic for scheduling.
    WeibullShape           DECIMAL(4,2) NOT NULL,
    IntervalNote           VARCHAR(400) NOT NULL
);
GO

/*
Ref_Reporting -- the settings that decide WHICH question gets answered.

These are not cosmetic. Each one silently changes every figure the project
publishes, so each one sits in a table with its reasoning attached rather than
as a literal inside a query.

ReportingAsOfDate in particular. Anchoring on 'the latest date in the data'
looks harmless and means the published answer moves the moment anyone loads one
more sortie -- so a figure quoted in a report stops matching the system that
produced it, and nobody can tell whether the fleet changed or the anchor did.
*/
CREATE TABLE dbo.Ref_Reporting (
    SettingName   VARCHAR(40)  NOT NULL PRIMARY KEY,
    SettingValue  VARCHAR(40)  NOT NULL,
    -- 400, not 300. These descriptions carry the reasoning for a setting that
    -- moves every published figure; a column too narrow to hold the reasoning
    -- is a column that quietly encourages leaving it out.
    [Description] VARCHAR(400) NOT NULL
);
GO

CREATE TABLE dbo.Ref_FleetTargets (
    MetricName    VARCHAR(40)   NOT NULL PRIMARY KEY,
    TargetValue   DECIMAL(10,2) NOT NULL,
    WarningValue  DECIMAL(10,2) NOT NULL,
    Direction     VARCHAR(15)   NOT NULL CHECK (Direction IN ('HigherBetter','LowerBetter')),
    Unit          VARCHAR(10)   NOT NULL CHECK (Unit IN ('Percent','Count','Hours','Ratio')),
    [Description] VARCHAR(220)  NOT NULL
);
GO

-- =============================================================================
-- REFERENCE DATA
-- =============================================================================

INSERT INTO dbo.Dim_MissionProfile (ProfileCode, ProfileName, TypicalPayloadKg, [Description]) VALUES
 ('COASTAL',  'Coastal survey',          12.0, 'Low altitude, stable air, long straight legs. The benign end of the envelope.'),
 ('URBAN',    'Urban inspection',        14.0, 'Short legs, frequent repositioning, many landings, moderate turbulence from buildings.'),
 ('MOUNTAIN', 'Mountain survey',         22.0, 'High density altitude, thermal turbulence, sustained high power settings.'),
 ('CARGO',    'Cargo relay',             28.0, 'Maximum payload, long duration, high continuous rotor loading.'),
 ('SAR',      'Search and rescue',       18.0, 'Unpredictable profile, frequent hover, often flown in the conditions others avoid.'),
 ('TRAINING', 'Training and check ride',  8.0, 'Light payload but an unusually high landing count: circuits and autorotation practice.');
GO

INSERT INTO dbo.Ref_StressModel (ProfileCode, StressMultiplier, CyclePenaltyHours, PayloadPenaltyPerKg, SourceNote) VALUES
 ('COASTAL',  1.000, 0.020, 0.0000,
  'Baseline. Nominal payload, stable air, minimal thermal cycling. All other profiles are expressed relative to this.'),
 ('URBAN',    1.350, 0.055, 0.0040,
  'Turbulence loading from building wake plus a high landing count. The cycle penalty dominates the hourly multiplier on short sorties.'),
 ('MOUNTAIN', 2.400, 0.060, 0.0085,
  'Sustained high power at density altitude, with thermal turbulence. The largest hourly multiplier in the fleet and the reason the finding exists.'),
 ('CARGO',    2.050, 0.040, 0.0110,
  'Continuous high rotor loading at maximum payload. Lower turbulence than mountain work but the highest payload penalty.'),
 ('SAR',      1.850, 0.070, 0.0060,
  'Hover-heavy with an unpredictable profile, frequently flown in degraded conditions. Wide variance around this figure.'),
 ('TRAINING', 1.150, 0.095,  0.0010,
  'Light payload reduces hourly loading, but circuit work produces far more landings per hour than any other profile. Training flies below the 12kg nominal, so the payload term goes NEGATIVE for this profile and removes stress -- which is the intent. A negative coefficient here would have added stress to a lighter aircraft.');
GO

INSERT INTO dbo.Dim_ComponentType (ComponentCode, ComponentName, PositionsPerAirframe, Criticality, LeadTimeFlightHours) VALUES
 ('ROTOR-ASSY', 'Rotor assembly and bearing', 4, 'FlightCritical',  18.0),
 ('MOTOR-ESC',  'Motor and speed controller', 4, 'FlightCritical',  12.0),
 ('BATT-PACK',  'Main battery pack',          2, 'FlightCritical',   8.0),
 ('GIMBAL',     'Payload gimbal',             1, 'MissionCritical', 24.0),
 ('AIRDATA',    'Air data and pitot module',  1, 'MissionCritical',  6.0),
 ('LANDGEAR',   'Landing gear assembly',      1, 'Degraded',         4.0);
GO

INSERT INTO dbo.Ref_ServiceInterval (ComponentCode, IntervalFlightHours, IntervalStressHours, WeibullShape, IntervalNote) VALUES
 ('ROTOR-ASSY', 150.0, 150.0, 2.60,
  'Bearing wear-out. Shape 2.6 means the failure rate rises steeply with accumulated stress -- the mean is a poor guide and the interval must be set on the distribution, not the average.'),
 ('MOTOR-ESC',  200.0, 200.0, 2.10,
  'Winding insulation and bearing degradation. Thermal cycling matters as much as running hours; the stress model has no temperature term, so cycling enters only through the per-landing cycle penalty and this interval is correspondingly approximate.'),
 ('BATT-PACK',  120.0, 120.0, 1.80,
  'Capacity fade. Deep discharge on high-payload profiles accelerates it well beyond what the hour meter suggests.'),
 ('GIMBAL',     300.0, 300.0, 1.40,
  'Servo and slip-ring wear. Nearly flat hazard: close to random failure, so condition monitoring earns less here than elsewhere.'),
 ('AIRDATA',    400.0, 400.0, 1.05,
  'Effectively random failure. Shape 1.05 means scheduled replacement buys almost nothing -- replacing it early replaces a good part with an equally failure-prone new one.'),
 ('LANDGEAR',   250.0, 250.0, 3.10,
  'Fatigue driven almost entirely by landing count rather than airborne time. The clearest case in the fleet for measuring cycles instead of hours.');
GO

INSERT INTO dbo.Ref_Reporting (SettingName, SettingValue, [Description]) VALUES
 ('ReportingAsOfDate', '2026-09-30',
  'The date every as-of figure is computed at. Pinned rather than derived from the data so a published number stays reproducible after the next load.'),
 ('AlertVibThreshold', '3.40',
  'Vibration multiple of a component''s own baseline at which an alert is raised. Set to the LOWEST threshold at which rotor-assembly precision reaches its 75 percent target -- the operating point a programme tuning for trustworthy alerts would actually choose. Lowering it buys lead time and loses precision; that trade-off is the point.'),
 ('HangarHoursPerWeek', '120.0',
  'Maintenance capacity available to the fleet per week. Changing it re-cuts the action queue, which is how the question "what if we add a bay" gets answered without editing anything.'),
 ('TrailingWindowMonths', '12',
  'Window for rate metrics such as unscheduled removals. Since-inception rates improve every month for reasons unrelated to maintenance, because early in a fleet life nothing has reached its first interval yet.');
GO

INSERT INTO dbo.Ref_FleetTargets (MetricName, TargetValue, WarningValue, Direction, Unit, [Description]) VALUES
 ('StressCompliancePct',     100.00, 95.00, 'HigherBetter', 'Percent',
  'Fitted components inside their interval measured in STRESS hours. The real compliance figure; 100% is the only passing value on flight-critical parts.'),
 ('HourCompliancePct',       100.00, 95.00, 'HigherBetter', 'Percent',
  'Fitted components inside their interval measured in FLIGHT hours. What the maintenance system enforces today, reported because the programme reports it.'),
 ('ActionableLeadTimePct',    70.00, 50.00, 'HigherBetter', 'Percent',
  'Share of predicted failures caught with enough remaining life to order and fit the part. The only prediction quality measure that changes a decision.'),
 ('UnscheduledRatePct',       15.00, 25.00, 'LowerBetter',  'Percent',
  'Unscheduled maintenance events as a share of all events. A fleet above this is being maintained by its failures.'),
 ('AirframeAvailabilityPct',  85.00, 75.00, 'HigherBetter', 'Percent',
  'Share of active airframes not grounded for maintenance at the reporting date.'),
 ('OverdueFlightCritical',     0.00,  2.00, 'LowerBetter',  'Count',
  'Flight-critical components past their stress interval and still fitted.'),
 ('PredictionPrecisionPct',   75.00, 60.00, 'HigherBetter', 'Percent',
  'Of components the model flags, the share that genuinely fail within the horizon. Low precision means crews stop believing the alerts.'),
 ('PredictionRecallPct',      80.00, 65.00, 'HigherBetter', 'Percent',
  'Of components that genuinely fail, the share the model flagged. Recall alone is not enough -- see ActionableLeadTimePct.');
GO

-- =============================================================================
-- Creation gate. Fail loudly rather than leave a half-built schema.
-- =============================================================================
DECLARE @missing VARCHAR(600) = '';
IF OBJECT_ID('dbo.Dim_Date','U')                IS NULL SET @missing += 'Dim_Date ';
IF OBJECT_ID('dbo.Dim_Base','U')                IS NULL SET @missing += 'Dim_Base ';
IF OBJECT_ID('dbo.Dim_Airframe','U')            IS NULL SET @missing += 'Dim_Airframe ';
IF OBJECT_ID('dbo.Dim_ComponentType','U')       IS NULL SET @missing += 'Dim_ComponentType ';
IF OBJECT_ID('dbo.Dim_MissionProfile','U')      IS NULL SET @missing += 'Dim_MissionProfile ';
IF OBJECT_ID('dbo.Fact_Sortie','U')             IS NULL SET @missing += 'Fact_Sortie ';
IF OBJECT_ID('dbo.Fact_ComponentInstall','U')   IS NULL SET @missing += 'Fact_ComponentInstall ';
IF OBJECT_ID('dbo.Fact_MaintenanceEvent','U')   IS NULL SET @missing += 'Fact_MaintenanceEvent ';
IF OBJECT_ID('dbo.Fact_SensorReading','U')      IS NULL SET @missing += 'Fact_SensorReading ';
IF OBJECT_ID('dbo.Ref_StressModel','U')         IS NULL SET @missing += 'Ref_StressModel ';
IF OBJECT_ID('dbo.Ref_ServiceInterval','U')     IS NULL SET @missing += 'Ref_ServiceInterval ';
IF OBJECT_ID('dbo.Ref_FleetTargets','U')        IS NULL SET @missing += 'Ref_FleetTargets ';
IF OBJECT_ID('dbo.Ref_Reporting','U')           IS NULL SET @missing += 'Ref_Reporting ';
IF @missing <> '' THROW 53001, 'FAILED to create the schema -- scroll up for the error.', 1;

-- Every mission profile must have a stress multiplier, or a sortie flown on it
-- would silently score zero damage.
IF EXISTS (SELECT 1 FROM dbo.Dim_MissionProfile p
           WHERE NOT EXISTS (SELECT 1 FROM dbo.Ref_StressModel s WHERE s.ProfileCode = p.ProfileCode))
    THROW 53002, 'Every mission profile needs a row in Ref_StressModel -- an unmodelled profile would accrue no wear.', 1;

-- Every component type must have an interval, for the same reason.
IF EXISTS (SELECT 1 FROM dbo.Dim_ComponentType c
           WHERE NOT EXISTS (SELECT 1 FROM dbo.Ref_ServiceInterval i WHERE i.ComponentCode = c.ComponentCode))
    THROW 53003, 'Every component type needs a row in Ref_ServiceInterval.', 1;

PRINT 'Schema created and verified: 5 dimensions, 4 facts, 4 reference tables.';
GO
