"""
================================================================================
Project 4 - Talon Robotics: Payload Deployment Delivery
App:     streamlit/app.py
Purpose: The programme board's front end. Five screens, each answering one
         question the case study answers, each ending in a decision.

WHAT THIS IS FOR

    A programme board opens this before the gate review to answer: is build 88
    ready to ship, where is it not, what do we book next week, and can we trust
    the answer. Every screen ends in the recommendation it supports and the
    person who acts on it.

NO ANALYTICAL LOGIC LIVES HERE, AND THAT IS DELIBERATE

    Every definition -- current, stale, meets policy, verification state,
    priority rank, action code, what an action costs in rig and airframe hours,
    the rig week, the data-quality checks -- is computed in SQL and arrives in
    an extract column. This app filters, sorts, counts flagged rows and draws.
    Re-deriving 'stale' in pandas would make a second definition, and the first
    time it disagreed with the Excel control nobody could say which was wrong.

    The rig capacity slider applies SQL's own IsThisWeek rule (sql/05) at
    another capacity: SQL's running total within capacity, and no item that
    needs the airframe. It re-cuts the queue, never re-ranks it; validate_app.py
    proves that at 180 it lists exactly SQL's IsThisWeek rows.

    RAG status is in no extract, so it is quoted, never derived: grey is what
    the programme reports; a board metric's card takes the status README's
    board gives it; other cards are red if they block shipping, amber if they
    are a schedule or data matter, green for the healthy part.

DATA DISCLOSURE
    Talon Robotics is fictional and all data is synthetic, generated by the
    scripts in sql/. No confidential data is used and no claim is made about
    any production system.
================================================================================
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st

EXTRACTS = Path(__file__).resolve().parent.parent / "erp_extracts"

# SQL figures no extract carries, quoted; validate_app.py fails if the literal
# moves. vw_VerificationQueue's capacity (six rigs x 30 h, sql/05); one Field run
# in airframe hours (Ref_TestLevelRank, sql/01); the gate usp_RunDataQualityChecks
# prints rather than returns (case study l.265; tolerance literal in sql/04).
SQL_RIG_HOURS_PER_WEEK = 180.0
SQL_FIELD_HOURS_PER_RUN = 8.0
SQL_GATE_PCT, SQL_GATE_TOLERANCE_PCT = 1.779, 2.000

st.set_page_config(page_title="Talon Robotics - Release Readiness Control", page_icon="=", layout="wide")

RED, AMBER, GREEN, GREY = "#c00000", "#bf8f00", "#548235", "#808080"
RAG = {"Red": RED, "Amber": AMBER, "Green": GREEN, "Grey": GREY}


@st.cache_data(show_spinner="Loading the committed extracts...")
def load_all() -> dict[str, pd.DataFrame]:
    names = ["readiness_kpi", "readiness_targets", "readiness_trend", "requirement_verification",
             "verification_policy", "subsystem_readiness", "build_churn", "verification_queue",
             "data_quality_summary", "raid_register"]
    # utf-8-sig: Export-Csv writes a byte-order mark, which would otherwise
    # become part of the first column's name.
    return {n: pd.read_csv(EXTRACTS / f"{n}.csv", encoding="utf-8-sig") for n in names}


def metric_card(column, label: str, value: str, rag: str, sub: str = "") -> None:
    colour = RAG.get(rag, GREY)
    column.markdown(
        f"""<div style="border-left:6px solid {colour};padding:0.4rem 0 0.4rem 0.9rem;margin-bottom:0.6rem">
        <div style="font-size:0.78rem;color:#555;text-transform:uppercase;letter-spacing:0.04em">{label}</div>
        <div style="font-size:2.0rem;font-weight:700;color:{colour};line-height:1.1">{value}</div>
        <div style="font-size:0.78rem;color:#666">{sub}</div></div>""",
        unsafe_allow_html=True,
    )


def decision(text: str) -> None:
    st.subheader("The decision")
    st.success(text)


data = load_all()
kpi = data["readiness_kpi"].iloc[0]
reqs = data["requirement_verification"]
must = reqs[reqs["Priority"] == "MustShip"]
as_of_build = int(kpi["AsOfBuild"])
rig_total, air_total = float(kpi["RigHoursOutstanding"]), float(kpi["AirframeHoursOutstanding"])

st.sidebar.title("Talon Robotics")
st.sidebar.caption("Release readiness control")
st.sidebar.markdown(f"**Reporting date** {kpi['AsOfDate']}  \n**Build** {as_of_build} (release candidate)")
st.sidebar.caption("Source: committed CSV extracts (erp_extracts/), exported from SQL Server")
st.sidebar.markdown("---")
st.sidebar.caption("Talon Robotics is fictional. All data is synthetic and generated by the scripts in "
                   "`sql/`. No confidential data is used and no claim is made about any production system.")

page = st.sidebar.radio("Screen", ["Complete or ready?", "Tested is not verified", "Where the gap is",
                                   "The verification queue", "Can the answer be trusted?"])


# =============================================================================
# 1. COMPLETE OR READY?
# =============================================================================
if page == "Complete or ready?":
    st.title("Is the payload ready to ship?")
    st.markdown(
        "The programme reports how much **work** is closed. Shipping depends on **evidence**. Every "
        "number below is correct, for the same programme at the same build. Only the third is about "
        "shipping."
    )

    trend = data["readiness_trend"].set_index("BuildNumber")
    gap = float(trend.loc[as_of_build, "ReadinessGapVsReported"])  # computed in SQL

    c1, c2, c3, c4 = st.columns(4)
    metric_card(c1, "Work items closed", f"{kpi['WorkItemCompletionPct']:.2f}%", "Grey",
                "What the programme reports: effort")
    metric_card(c2, "Requirements with passing evidence", f"{kpi['VerificationCoveragePct']:.2f}%",
                "Grey", "A test passed on some build, at some point")
    metric_card(c3, "Must-ship requirements ready to ship", f"{kpi['ShipReadinessPct']:.2f}%",
                "Red", "Evidence that counts and still applies")
    metric_card(c4, "The gap", f"{gap:.2f} points", "Red", "Completion minus readiness")

    st.info(
        "**A verification is evidence about one build.** If a requirement passed on build 62 and its "
        "subsystem changed in build 71, the requirements tool still says Verified, and it is describing "
        "software that no longer exists. Staleness here is intervening change, never age."
    )

    not_ready = must[must["IsCurrent"] == 0]
    c1, c2, c3, c4 = st.columns(4)
    metric_card(c1, "Must-ship without current, admissible evidence",
                f"{len(not_ready)} of {int(kpi['MustShipCount'])}", "Red",
                "The requirements build 88 would ship without")
    metric_card(c2, "Stale verification", f"{kpi['StaleVerificationPct']:.2f}%", "Amber",
                "Of policy-compliant evidence, overtaken by change")
    metric_card(c3, "Policy compliance", f"{kpi['PolicyCompliancePct']:.2f}%", "Red",
                "Of requirements with evidence, evidence that counts")
    metric_card(c4, "Critical RAID items open", f"{int(kpi['CriticalRAIDOpen'])}", "Red",
                "Open or mitigating, Critical exposure band")

    st.subheader("The two numbers, build by build")
    st.line_chart(trend[["WorkItemCompletionPct", "VerificationCoveragePct", "ShipReadinessPct"]], height=300)
    st.caption(
        "Every point is the same SQL procedure (usp_ReadinessTrend) evaluated as of that build. "
        f"Completion never fell below {trend['WorkItemCompletionPct'].min():.0f}% at any build shown, and "
        f"the gap never closed below {trend['ReadinessGapVsReported'].min():.0f} points: reporting only "
        "completion is what kept it invisible for most of a year."
    )

    st.subheader("The whole board")
    hours = pd.DataFrame([  # no target is set for either resource
        {"MetricName": "RigHoursOutstanding", "Unit": "Hours",
         "Note": f"{rig_total / SQL_RIG_HOURS_PER_WEEK:.1f} rig-weeks at {SQL_RIG_HOURS_PER_WEEK:.0f} a week"},
        {"MetricName": "AirframeHoursOutstanding", "Unit": "Hours",
         "Note": f"{air_total / SQL_FIELD_HOURS_PER_RUN:.0f} flights; no airframe capacity to divide by"},
    ])
    board = pd.concat([
        data["readiness_targets"][["MetricName", "Unit", "TargetValue", "WarningValue", "Direction"]], hours,
    ]).rename(columns={"MetricName": "Metric", "TargetValue": "Target", "WarningValue": "Warning"})
    board["Note"] = board["Note"].fillna("")
    fmt = {"Count": "{:.0f}", "Hours": "{:.1f}"}  # everything else is a percentage
    board.insert(1, "Value", [fmt.get(u, "{:.2f}").format(float(kpi[m]))
                              for m, u in zip(board["Metric"], board["Unit"])])
    st.dataframe(board, width="stretch", hide_index=True)
    st.caption(
        "Values from readiness_kpi.csv, thresholds from readiness_targets.csv. Red/Amber/Green status "
        "lives in the Excel control and the Power BI model, not in the extracts, so it is not "
        "re-derived here. Card colours: grey is what the programme reports; a card showing a board "
        "metric takes the status these thresholds give it (the README's 'Headline figures' board); "
        "other cards are red if they block shipping, amber if they are a schedule or data matter."
    )

    decision(
        f"**Do not ship build {as_of_build}.** {len(not_ready)} of {int(kpi['MustShipCount'])} must-ship "
        "requirements have no current, admissible evidence. This is not a judgement about risk "
        "appetite: the evidence to make that judgement does not exist. **Owner: programme board.** And "
        "from now on, report readiness and completion side by side."
    )


# =============================================================================
# 2. TESTED IS NOT VERIFIED
# =============================================================================
elif page == "Tested is not verified":
    st.title("Most of the evidence is real. A quarter of it no longer applies.")
    st.markdown(
        "Three things must be true before a requirement can ship: **evidence exists**, **the evidence "
        "counts** (the right test level, by someone entitled to produce it), and **the evidence still "
        "applies** (nothing it depended on has moved)."
    )

    order = ["Current", "Stale - subsystem changed", "Stale - requirement changed",
             "Insufficient evidence", "No evidence"]
    states = pd.DataFrame({
        "Verification state": order,
        "Requirements": [int((reqs["VerificationState"] == s).sum()) for s in order],
        "Of which must-ship": [int((must["VerificationState"] == s).sum()) for s in order],
    })
    states.loc[len(states)] = ["Total baselined", len(reqs), len(must)]
    st.dataframe(states, width="stretch", hide_index=True)

    c1, c2, c3 = st.columns(3)
    never = int(kpi["NoEvidenceCount"])
    metric_card(c1, "Never tested", f"{never}", "Green",
                f"{100 * never / int(kpi['Requirements']):.1f}% of {int(kpi['Requirements'])} "
                "- why coverage looks healthy")
    metric_card(c2, "Evidence overtaken by change", f"{int(kpi['StaleCount'])}", "Red",
                "Same subsystem changed since, or the requirement was modified")
    metric_card(c3, "Evidence that never counted", f"{int(kpi['InsufficientCount'])}", "Red",
                "Below the required grade, or produced by its own author")

    st.subheader("What counts as evidence")
    st.markdown(
        "`Ref_VerificationPolicy` is the most contestable input in the analysis, so it is a table a "
        "systems engineer can argue with, not a rule inside a query."
    )
    st.dataframe(data["verification_policy"], width="stretch", hide_index=True)

    # Both counts are SQL's own data-quality checks (sql/04), not thresholds here.
    dq = data["data_quality_summary"].set_index("AnomalyType")
    under_levelled = int(dq.loc["UNDER_LEVELLED_VERIFICATION", "Anomalies"])
    c1, c2, c3 = st.columns(3)
    metric_card(c1, "Passed below the required level", f"{under_levelled}", "Red",
                "And none that meets it: a safety behaviour signed off by a unit test")
    metric_card(c2, "Passed by their own owner", f"{int(dq.loc['SELF_VERIFIED_SAFETY', 'Anomalies'])}",
                "Red", "And no admissible evidence; the policy requires an independent witness")
    metric_card(c3, "Policy compliance", f"{kpi['PolicyCompliancePct']:.2f}%", "Red",
                "Of requirements with evidence, evidence that counts")
    st.caption(
        f"The two groups overlap, so together they are the {int(kpi['InsufficientCount'])} requirements "
        "whose evidence never counted. Both read as a pass on every dashboard the programme currently "
        "runs. Neither is admissible evidence, and for the Regulatory subset neither would be accepted "
        "by the certifying authority."
    )

    st.subheader("Every baselined requirement")
    c1, c2, c3 = st.columns(3)
    pick_state = c1.multiselect("Verification state", order)
    pick_sub = c2.multiselect("Subsystem", sorted(reqs["SubsystemName"].unique()))
    only_must = c3.checkbox("Only must-ship", value=True)
    view = must if only_must else reqs
    if pick_state:
        view = view[view["VerificationState"].isin(pick_state)]
    if pick_sub:
        view = view[view["SubsystemName"].isin(pick_sub)]
    st.caption(f"{len(view):,} of {len(reqs):,} baselined requirements")
    st.dataframe(
        view[["RequirementID", "ReqType", "Priority", "SubsystemName", "MinTestLevel", "VerificationState",
              "LastPassBuild", "LastGoodBuild", "InterveningBuilds", "PassingButUnderLevelled",
              "PassingButSelfVerified", "Title"]], width="stretch", hide_index=True)

    # What each action costs is SQL's (fn_VerificationCost): read, never re-priced.
    queue = data["verification_queue"].sort_values("PriorityRank")
    raise_level = queue[queue["ActionCode"] == "RAISE_TEST_LEVEL"]
    witness = queue[queue["ActionCode"] == "INDEPENDENT_WITNESS"]
    signature = witness[witness["RigHours"] + witness["AirframeHours"] == 0]
    rerun = witness.drop(signature.index)

    st.subheader("Waiting for a witness")
    st.dataframe(witness.merge(reqs[["RequirementID", "LastPassBuild"]], on="RequirementID")[
        ["RequirementID", "ReqType", "Priority", "SubsystemCode", "LastPassBuild", "RigHours",
         "RecommendedAction"]], width="stretch", hide_index=True)
    st.caption("SQL costs a self-run pass that nothing has touched since at 0 hours: a second engineer "
               "countersigns it. A pass overtaken by change is re-run on the release candidate, witnessed.")

    decision(
        f"**Schedule the {under_levelled} under-levelled requirements explicitly** - they read as passes "
        "today, so none has been allocated the level its policy demands: "
        f"{int((raise_level['RigHours'] > 0).sum())} need a rig slot and "
        f"{int((raise_level['AirframeHours'] > 0).sum())} a flight, and "
        f"{int(raise_level['NeedsNewCase'].sum())} need a test written first. **Owner: test manager.** "
        f"**Countersign the {len(signature)} self-verified requirements a signature alone would fix** "
        f"({' and '.join(signature['RequirementID'])}) - the cheapest readiness the programme can buy; "
        f"**re-run {' and '.join(rerun['RequirementID'])} under a witness**, because a signature now "
        "would certify superseded evidence. **Owner: Quality.**"
    )


# =============================================================================
# 3. WHERE THE GAP IS
# =============================================================================
elif page == "Where the gap is":
    st.title("The gap sits exactly where the design is still moving")
    sub = data["subsystem_readiness"].sort_values("ReadinessPct")
    worst, rest = sub.head(2), sub.iloc[2:]
    all_must = int(kpi["MustShipCount"])

    c1, c2, c3 = st.columns(3)
    for column, (_, row) in zip([c1, c2], worst.iterrows()):
        metric_card(column, row["SubsystemName"], f"{row['ReadinessPct']:.2f}%", "Red",
                    f"{row['Criticality']} - {int(row['MustShip'])} must-ship - "
                    f"changed in {int(row['BuildsChanged'])} builds")
    metric_card(c3, "Their share of what must ship",
                f"{100 * worst['MustShip'].sum() / all_must:.0f}%", "Red",
                f"{int(worst['MustShip'].sum())} of {all_must} must-ship requirements")

    st.markdown(
        f"The other {len(rest)} subsystems carry {int(rest['MustShip'].sum())} must-ship requirements "
        f"and sit between **{rest['ReadinessPct'].min():.0f}% and {rest['ReadinessPct'].max():.0f}%** "
        f"ready, changed in {int(rest['BuildsChanged'].min())} to {int(rest['BuildsChanged'].max())} "
        "builds. The two worst subsystems are also the two most-changed."
    )
    st.dataframe(
        sub[["SubsystemName", "Criticality", "MustShip", "CurrentMustShip", "ReadinessPct",
             "BuildsChanged", "LinesChanged", "LastChangeBuild", "StaleByCode", "StaleByReq",
             "Insufficient", "NoEvidence", "RigHoursOutstanding", "AirframeHoursOutstanding"]],
        width="stretch", hide_index=True)

    # sort=False keeps the readiness order `sub` is already in.
    c1, c2 = st.columns(2)
    c1.subheader("Ship readiness, %")
    c1.bar_chart(sub.set_index("SubsystemCode")["ReadinessPct"], height=280, sort=False)
    c2.subheader("Builds that changed it")
    c2.bar_chart(sub.set_index("SubsystemCode")["BuildsChanged"], height=280, sort=False)

    st.subheader("Lines changed, build by build")
    churn = data["build_churn"]
    pick = st.multiselect("Subsystem", sorted(churn["SubsystemCode"].unique()),
                          default=list(worst["SubsystemCode"]))
    shown = churn[churn["SubsystemCode"].isin(pick)] if pick else churn
    st.bar_chart(shown.pivot_table(index="BuildNumber", columns="SubsystemCode", values="LinesChanged",
                                   aggfunc="sum").fillna(0), height=300)
    st.caption(
        "A subsystem verified once and then changed in forty-five subsequent builds is not behind on "
        "test execution - it is still being designed. Re-running its suite today buys evidence the next "
        "build invalidates."
    )

    decision(
        f"**Freeze {' and '.join(worst['SubsystemName'])}, or accept that their verification cannot "
        f"close.** At {' and '.join(str(int(b)) for b in worst['BuildsChanged'])} builds changed, "
        "re-running their suites buys evidence the next build invalidates. Freeze the interface, then "
        "verify. **Owner: chief engineer.**"
    )


# =============================================================================
# 4. THE VERIFICATION QUEUE
# =============================================================================
elif page == "The verification queue":
    st.title("What to book next week")
    queue = data["verification_queue"].sort_values("PriorityRank").copy()

    st.markdown(
        "The queue is ranked in SQL by a four-term priority score - must-ship weight, criticality, how "
        "badly the evidence fails, and how much has changed since. Each item is costed by what its "
        "action needs, in the resource it needs: **rig hours** on the hardware-in-the-loop rigs, "
        "**airframe hours** for Field runs. SQL keeps the running total of rig hours in rank order; the "
        "slider re-cuts the queue against that running total. **It does not re-rank it.**"
    )

    capacity = st.slider("Rig hours available per week", min_value=60.0, max_value=600.0,
                         value=SQL_RIG_HOURS_PER_WEEK, step=30.0,
                         help="SQL cut the queue at 180: six rigs at 30 bookable hours. At any "
                              "capacity, an item that needs a flight is never booked into the rig week.")
    # SQL's IsThisWeek rule (sql/05 fn_VerificationQueue) at the chosen capacity.
    queue["InRigWeek"] = (queue["CumulativeRigHours"] <= capacity) & (queue["AirframeHours"] == 0)
    this_week = queue[queue["InRigWeek"]]

    c1, c2, c3, c4 = st.columns(4)
    metric_card(c1, "Outstanding requirements", f"{len(queue)}", "Red", f"Not current at build {as_of_build}")
    metric_card(c2, "In the first rig week", f"{len(this_week)}", "Amber",
                f"Within {capacity:.0f} rig hours, and no flights")
    metric_card(c3, "Rig hours to clear", f"{rig_total:,.1f}", "Amber", "Costed by what each action needs")
    metric_card(c4, "Rig-weeks to clear", f"{rig_total / capacity:.1f}", "Amber",
                "At this capacity - a capacity statement, not a date")
    c1, c2, c3 = st.columns([1, 1, 2])
    metric_card(c1, "Airframe hours to clear", f"{air_total:,.1f}", "Amber", "Never divided by rig capacity")
    metric_card(c2, "Flights", f"{air_total / SQL_FIELD_HOURS_PER_RUN:.0f}", "Amber",
                f"On {int((queue['AirframeHours'] > 0).sum())} items, at "
                f"{SQL_FIELD_HOURS_PER_RUN:.0f} airframe hours a run")
    c3.markdown(
        "Field evidence needs the airframe - one aircraft, weather and a crew - so its hours are "
        "reported beside the rig figure and never divided by rig capacity, and no item that needs a "
        "flight is booked into the rig week. **The data holds no airframe capacity, so these hours are "
        "costed, not scheduled**; with one aircraft they are the likelier constraint."
    )

    st.subheader("The action follows the state, not the rank")
    mix = (queue.groupby("ActionCode")
                .agg(Requirements=("RequirementID", "size"), RigHours=("RigHours", "sum"),
                     AirframeHours=("AirframeHours", "sum"),
                     NeedRig=("RigHours", lambda h: int((h > 0).sum())),
                     NeedFlight=("AirframeHours", lambda h: int((h > 0).sum())),
                     NewTestFirst=("NeedsNewCase", "sum"), InRigWeek=("InRigWeek", "sum"))
                .reset_index().sort_values("Requirements", ascending=False))
    st.dataframe(mix, width="stretch", hide_index=True)
    st.caption(
        "SQL costs every test at or above the level the policy demands, one new test where none exists "
        "at that level yet, and nothing for a signature. **Pricing a test that must be written first at "
        "a single run is a floor.**"
    )
    st.markdown(
        "| Action | Who does it |\n|---|---|\n"
        "| `RERUN` | Test engineer, needs a rig slot |\n"
        "| `RAISE_TEST_LEVEL` | Test engineer: a rig slot or a flight, often a new test first |\n"
        "| `REVIEW_THEN_RERUN` | Systems engineer **first**, then test |\n"
        "| `INDEPENDENT_WITNESS` | A second engineer's signature; a witnessed re-run if the evidence "
        "has since been overtaken |\n"
        "| `VERIFY` | Write the test, then run it |"
    )
    witness = queue[queue["ActionCode"] == "INDEPENDENT_WITNESS"]
    signature = witness[witness["RigHours"] + witness["AirframeHours"] == 0]
    st.caption(
        "Re-running a test when the requirement itself changed risks certifying against the old "
        "wording, so that case goes to a systems engineer before it goes near a rig. INDEPENDENT_WITNESS "
        f"costs a signature, not rig time, when nothing has changed since the pass - {len(signature)} of "
        f"the {len(witness)} here; the rest need a re-run under a witness "
        f"({witness['RigHours'].sum():.1f} rig hours)."
    )

    st.subheader("Hardware time is the constraint, not test throughput")
    levels = data["verification_policy"].sort_values("MinTestLevelRank")["MinTestLevel"].unique()
    st.bar_chart(queue.groupby("MinTestLevel")[["RigHours", "AirframeHours"]].sum().reindex(levels),
                 height=260, sort=False)
    free = int(((queue["RigHours"] == 0) & (queue["AirframeHours"] == 0)).sum())
    st.caption(
        "Hours outstanding by the test level each requirement's policy demands. Every hour is hardware "
        "time - the rigs for hardware-in-the-loop, the airframe for Field - so 'verification is behind' "
        f"and 'we cannot get rig time' are largely one item on the risk register. Not entirely: {free} of "
        f"the {len(queue)} outstanding items need neither a rig nor a flight. A seventh rig shortens only "
        "the rig hours."
    )

    st.subheader("The queue")
    view = this_week if st.checkbox("Show only the first rig week", value=True) else queue
    st.dataframe(
        view[["PriorityRank", "RequirementID", "SubsystemCode", "ReqType", "Priority",
              "Criticality", "MinTestLevel", "InterveningBuilds", "PriorityScore", "ActionCode",
              "RigHours", "AirframeHours", "NeedsNewCase", "CumulativeRigHours", "OwnerName",
              "OwnerTeam", "RecommendedAction"]], width="stretch", hide_index=True)

    decision(
        f"**Treat rig and airframe time as the schedule driver, not test throughput.** {rig_total:,.0f} "
        f"rig hours outstanding against {SQL_RIG_HOURS_PER_WEEK:.0f} a week, plus {air_total:,.0f} "
        "airframe hours on one aircraft. A seventh rig shortens the rig work but not the flights; more "
        "test engineers shorten neither. **Owner: programme board.**"
    )


# =============================================================================
# 5. CAN THE ANSWER BE TRUSTED?
# =============================================================================
else:
    st.title("What is wrong with the data, and does the answer survive it?")
    dq = data["data_quality_summary"]
    clean = int((dq["Anomalies"] == 0).sum())

    st.markdown(
        f"{len(dq)} behavioural checks run. **{clean} of them found nothing and are reported anyway** - "
        "a summary listing only what was found cannot distinguish *we looked and it was clean* from *we "
        "never looked*."
    )
    st.dataframe(
        dq[["AnomalyType", "EntityType", "Severity", "ImpactClass", "CountsTowardExposure", "Anomalies",
            "PopulationScanned", "AnomalyRatePct", "WhatItMeans"]], width="stretch", hide_index=True)

    st.subheader("The gate: the answer survives the data")
    exposure = dq[dq["CountsTowardExposure"] == 1]
    fired = exposure[exposure["Anomalies"] > 0]
    policy = dq[dq["ImpactClass"] == "Policy"]
    c1, c2, _ = st.columns(3)
    metric_card(c1, "Must-ship resting on flagged data", f"{SQL_GATE_PCT:.3f}%", "Green",
                "Quoted from usp_RunDataQualityChecks")
    metric_card(c2, "Gate tolerance", f"{SQL_GATE_TOLERANCE_PCT:.3f}%", "Grey", "@MaxAffectedMustShipPct")
    st.markdown(
        "The gate does not count defective rows. It asks what share of **must-ship requirements** has a "
        f"readiness answer resting on data a check has flagged. **It passes: {SQL_GATE_PCT:.3f}% against "
        f"a {SQL_GATE_TOLERANCE_PCT:.3f}% tolerance - a margin, not comfort.**\n\n"
        f"Why it passes: only the {len(exposure)} checks with `CountsTowardExposure = 1` feed the gate, "
        f"and only {len(fired)} of them found anything - "
        + ", ".join(f"{r.AnomalyType} ({int(r.Anomalies)} of {int(r.PopulationScanned):,} "
                    f"{r.EntityType} rows)" for r in fired.itertuples())
        + f" - so the whole {SQL_GATE_PCT:.3f}% rests on "
        + ("that check" if len(fired) == 1 else "those checks")
        + ". The procedure prints its result rather than exporting it, so the figure is quoted from the "
        "case study; `EXEC dbo.usp_RunDataQualityChecks` recomputes it.\n\n"
        f"**Policy breaches are deliberately excluded** ({len(policy)} checks, "
        f"{int(policy['Anomalies'].sum())} findings). A safety requirement verified by its own owner is "
        "accurate data recording a practice that should not have happened; the KPI layer holds it to "
        "account. Conflating 'the record is wrong' with 'the practice is wrong' makes both harder to fix."
    )

    st.subheader("The RAID register")
    raid = data["raid_register"]
    open_raid = raid[raid["IsOpen"] == 1]
    due_before = int(dq.set_index("AnomalyType").loc["RAID_DUE_BEFORE_RAISED", "Anomalies"])
    c1, c2, c3 = st.columns(3)
    metric_card(c1, "Critical RAID items open", f"{int(kpi['CriticalRAIDOpen'])}", "Red",
                f"Of {len(open_raid)} open or mitigating")
    metric_card(c2, "Open RAID items overdue", f"{kpi['OverdueRAIDPct']:.2f}%", "Red",
                f"{int(open_raid['IsOverdue'].sum())} of {len(open_raid)}")
    metric_card(c3, "Due before they were raised", f"{due_before}", "Amber",
                "A data defect - excluded from overdue, reported instead")

    only_critical = st.checkbox("Only the Critical exposure band")
    view = open_raid[open_raid["ExposureBand"] == "Critical"] if only_critical else open_raid
    st.dataframe(
        view[["RAIDID", "RAIDType", "SubsystemName", "ExposureScore", "ExposureBand",
              "RAIDStatus", "DueDate", "IsOverdue", "DaysOverdue", "OwnerName",
              "OwnerTeam", "Title", "MitigationNote"]], width="stretch", hide_index=True)

    decision(
        f"**Trust the readiness answer; fix the register.** The gate passes at {SQL_GATE_PCT:.3f}% "
        f"against {SQL_GATE_TOLERANCE_PCT:.3f}% - a margin, not comfort - so the "
        f"{kpi['ShipReadinessPct']:.2f}% readiness answer stands on this data. **Re-baseline the "
        f"{due_before} RAID items due before they were raised** - trivial to fix. IsOverdue excludes "
        "them, so they cannot inflate the overdue rate, but while open they sit in its denominator, and "
        "none can ever be reported overdue until its dates are corrected. **Owner: PMO.**"
    )
