"""
================================================================================
Project 5 - Meridian UAV Services: Predictive Maintenance
App:     streamlit/app.py
Purpose: The operational front end. Five screens, each answering one question.

WHAT THIS IS FOR

    A maintenance controller opens this on a Monday morning to answer: which
    aircraft do I ground this week, what do I order, and is the alarm system
    telling me anything I can act on.

    It is not a chart gallery. Every screen ends in a decision, and the two
    controls that matter -- hangar capacity and the alarm threshold -- change
    the answer rather than the appearance.

NO ANALYTICAL LOGIC LIVES HERE, AND THAT IS DELIBERATE

    Every definition -- overdue, hidden-overdue, priority rank, actionable lead
    time -- is computed in SQL and arrives already computed. This app filters,
    sorts and draws.

    The temptation is to reimplement 'overdue' in pandas because it is three
    lines. Then there are two definitions, they drift, and the first time the
    dashboard disagrees with the maintenance system nobody can say which is
    wrong. Project 4 spent a day reconciling Excel against Power BI for exactly
    that reason.

    The two interactive controls are therefore built so they CANNOT duplicate
    logic:
      * the capacity slider re-cuts a queue SQL has already ranked -- a running
        total, not a ranking;
      * the threshold slider reads a sweep SQL has already evaluated at every
        threshold, rather than re-scoring anything.

DATA DISCLOSURE
    Meridian UAV Services is fictional and all data is synthetic. No
    confidential data is used and no claim is made about any production system.
================================================================================
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "python"))
import data_access  # noqa: E402

st.set_page_config(
    page_title="Meridian UAV - Fleet Maintenance Control",
    page_icon="=",
    layout="wide",
)

RED, AMBER, GREEN, GREY = "#c00000", "#bf8f00", "#548235", "#808080"
RAG = {"Red": RED, "Amber": AMBER, "Green": GREEN, "Grey": GREY}


@st.cache_data(show_spinner="Loading from SQL Server or the extracts...")
def load_all() -> dict[str, pd.DataFrame]:
    keys = [
        "fleet_kpi", "base_scorecard", "component_wear", "action_queue",
        "threshold_sweep", "alert_evaluation", "component_life", "reporting",
        "component_type", "service_interval",
    ]
    return {k: data_access.load(k) for k in keys}


@st.cache_data
def source_label() -> str:
    return data_access.describe_source()


def metric_card(column, label: str, value: str, rag: str, sub: str = "") -> None:
    colour = RAG.get(rag, GREY)
    column.markdown(
        f"""<div style="border-left:6px solid {colour};padding:0.4rem 0 0.4rem 0.9rem;margin-bottom:0.6rem">
        <div style="font-size:0.78rem;color:#555;text-transform:uppercase;letter-spacing:0.04em">{label}</div>
        <div style="font-size:2.0rem;font-weight:700;color:{colour};line-height:1.1">{value}</div>
        <div style="font-size:0.78rem;color:#666">{sub}</div></div>""",
        unsafe_allow_html=True,
    )


data = load_all()
kpi = data["fleet_kpi"].set_index("MetricName")
settings = dict(zip(data["reporting"]["SettingName"], data["reporting"]["SettingValue"]))
as_of = settings.get("ReportingAsOfDate", "2026-09-30")

st.sidebar.title("Meridian UAV")
st.sidebar.caption("Fleet maintenance control")
st.sidebar.markdown(f"**Reporting date** {as_of}")
st.sidebar.caption(f"Source: {source_label()}")
st.sidebar.markdown("---")
st.sidebar.caption(
    "Meridian UAV Services is fictional. All data is synthetic and generated by "
    "the scripts in `sql/`. No confidential data is used and no claim is made "
    "about any production system."
)

page = st.sidebar.radio(
    "Screen",
    ["The two answers", "Where the gap is", "The queue", "Is the alarm useful?", "Data quality"],
)


# =============================================================================
# 1. THE TWO ANSWERS
# =============================================================================
if page == "The two answers":
    st.title("Is this fleet inside its maintenance intervals?")
    st.markdown(
        "Both numbers below are correct. They are the **same components**, "
        "the **same intervals**, and the **same day**. They differ only in the "
        "unit the interval is measured in."
    )

    c1, c2, c3 = st.columns(3)
    hour = kpi.loc["HourCompliancePct"]
    stress = kpi.loc["StressCompliancePct"]
    gap = float(hour["MetricValue"]) - float(stress["MetricValue"])

    metric_card(c1, "Compliant on FLIGHT HOURS", f"{hour['MetricValue']:.2f}%",
                hour["RAGStatus"], "What the maintenance system reports today")
    metric_card(c2, "Compliant on STRESS HOURS", f"{stress['MetricValue']:.2f}%",
                stress["RAGStatus"], "Measured in the unit the wear accrues in")
    metric_card(c3, "The gap", f"{gap:.2f} pts", "Red",
                "Components past due that no report shows")

    st.info(
        "**An hour is not a unit of wear.** An hour of mountain survey at 22kg and an "
        "hour of coastal survey at 12kg damage a rotor bearing by very different "
        "amounts, and an hour of circuit training produces ten landings where cargo "
        "relay produces one. The interval is enforced in hours because that is what "
        "the hour meter produces, not because that is how the part wears."
    )

    wear = data["component_wear"]
    hidden = wear[wear["IsHiddenOverdue"] == 1]
    hidden_fc = hidden[hidden["Criticality"] == "FlightCritical"]

    c1, c2, c3 = st.columns(3)
    metric_card(c1, "Past due on stress, inside the hour interval",
                f"{len(hidden)}", "Red", "Invisible to every current report")
    metric_card(c2, "...of which flight-critical", f"{len(hidden_fc)}", "Red",
                "Failure grounds the aircraft")
    unsched = kpi.loc["UnscheduledRatePct"]
    metric_card(c3, "Unscheduled removal rate", f"{unsched['MetricValue']:.2f}%",
                unsched["RAGStatus"],
                f"Target {unsched['TargetValue']:.0f}% - the fleet is maintained by its failures")

    st.subheader("The whole board")
    board = data["fleet_kpi"][["MetricName", "MetricValue", "TargetValue", "RAGStatus", "Description"]]
    st.dataframe(board, width="stretch", hide_index=True)


# =============================================================================
# 2. WHERE THE GAP IS
# =============================================================================
elif page == "Where the gap is":
    st.title("The fleet average describes none of the four bases")
    base = data["base_scorecard"].sort_values("StressCompliancePct")

    st.markdown(
        "**StressRatio** is the whole explanation: stress hours accrued per logged "
        "flight hour. Read across - the hour meter cannot tell these bases apart, "
        "and the work they fly is not remotely comparable."
    )
    st.dataframe(
        base[["BaseCode", "BaseName", "Airframes", "StressRatio", "HourCompliancePct",
              "StressCompliancePct", "ComplianceGapPoints", "HiddenOverdue",
              "UnscheduledRatePct"]],
        width="stretch", hide_index=True,
    )

    c1, c2 = st.columns(2)
    c1.subheader("Stress accrued per flight hour")
    c1.bar_chart(base.set_index("BaseCode")["StressRatio"], height=280)
    c2.subheader("Compliance, both ways")
    c2.bar_chart(
        base.set_index("BaseCode")[["HourCompliancePct", "StressCompliancePct"]],
        height=280,
    )

    st.caption(
        "Highland and Port are not worse-run bases. They fly mountain and cargo work, "
        "which is what the multiplier is measuring. The Academy is the one worth "
        "pausing on: it flies the lightest payloads and the fewest hours in the fleet, "
        "and circuit training produces so many landings that it wears its aircraft "
        "harder than the cargo hub."
    )

    st.subheader("Every fitted component")
    wear = data["component_wear"]
    c1, c2, c3 = st.columns(3)
    pick_base = c1.multiselect("Base", sorted(wear["BaseCode"].unique()))
    pick_comp = c2.multiselect("Component", sorted(wear["ComponentCode"].unique()))
    only_hidden = c3.checkbox("Only past due on stress but not on hours", value=True)

    view = wear.copy()
    if pick_base:
        view = view[view["BaseCode"].isin(pick_base)]
    if pick_comp:
        view = view[view["ComponentCode"].isin(pick_comp)]
    if only_hidden:
        view = view[view["IsHiddenOverdue"] == 1]

    st.caption(f"{len(view):,} of {len(wear):,} fitted components")
    st.dataframe(
        view[["TailNumber", "BaseCode", "ComponentCode", "PositionNo", "ComponentSerial",
              "Criticality", "FlightHours", "PctOfHourInterval",
              "StressHours", "PctOfStressInterval", "StressPerFlightHour",
              "ProjectedFlightHoursToStressLimit"]]
        .sort_values("PctOfStressInterval", ascending=False),
        width="stretch", hide_index=True,
    )


# =============================================================================
# 3. THE QUEUE
# =============================================================================
elif page == "The queue":
    st.title("What to do this week")
    queue = data["action_queue"].copy()
    default_capacity = float(settings.get("HangarHoursPerWeek", 120.0))

    st.markdown(
        "The queue is ranked in SQL: flight-critical first, then already overdue "
        "before merely projected, then furthest past its limit. The slider below "
        "re-cuts it - **it does not re-rank it**, because the ranking is a "
        "definition and definitions do not live in a dashboard."
    )

    capacity = st.slider(
        "Hangar hours available this week", min_value=40.0, max_value=400.0,
        value=default_capacity, step=10.0,
        help="Adding a bay is roughly 40 hours a week. This answers what that buys.",
    )

    # A running total over a queue SQL already ordered. No ranking logic here.
    queue = queue.sort_values("PriorityRank")
    queue["CumulativeJobHours"] = queue["JobHours"].cumsum()
    queue["InThisWeek"] = queue["CumulativeJobHours"] <= capacity

    this_week = queue[queue["InThisWeek"]]
    total_hours = float(queue["JobHours"].sum())

    c1, c2, c3, c4 = st.columns(4)
    metric_card(c1, "Outstanding jobs", f"{len(queue)}", "Red", "Across the whole fleet")
    metric_card(c2, "Schedulable this week", f"{len(this_week)}", "Amber",
                f"Within {capacity:.0f} hangar hours")
    metric_card(c3, "Total hangar hours", f"{total_hours:,.1f}", "Red", "To clear the backlog")
    weeks = total_hours / capacity if capacity else float("nan")
    metric_card(c4, "Weeks to clear", f"{weeks:.1f}", "Red", "At the current capacity")

    st.subheader("The mix of work, by action")
    mix = (queue.groupby("ActionCode")
                .agg(Jobs=("InstallKey", "size"), HangarHours=("JobHours", "sum"))
                .reset_index()
                .sort_values("Jobs", ascending=False))
    st.dataframe(mix, width="stretch", hide_index=True)
    st.caption(
        "These need different people. GROUND_AND_REPLACE needs a bay and a technician; "
        "ORDER_PART_NOW needs a purchase order and costs no hangar time at all, which "
        "is why it carries zero job hours. Lumping them together as 'overdue' loses "
        "the only distinction that decides who acts."
    )

    st.subheader("The queue")
    show_week_only = st.checkbox("Show only what fits in this week", value=True)
    view = this_week if show_week_only else queue
    st.dataframe(
        view[["PriorityRank", "TailNumber", "BaseCode", "ComponentCode", "PositionNo",
              "Criticality", "PctOfHourInterval", "PctOfStressInterval",
              "ProjectedFlightHoursToStressLimit", "LeadTimeFlightHours",
              "ActionCode", "JobHours", "CumulativeJobHours", "RecommendedAction"]],
        width="stretch", hide_index=True,
    )


# =============================================================================
# 4. IS THE ALARM USEFUL?
# =============================================================================
elif page == "Is the alarm useful?":
    st.title("The alarm is accurate. That is not the same as useful.")
    sweep = data["threshold_sweep"].copy()
    intervals = data["component_type"].set_index("ComponentCode")["LeadTimeFlightHours"].to_dict()
    pinned = float(settings.get("AlertVibThreshold", 3.40))

    st.markdown(
        "A prediction is worth its **lead time**, not its accuracy. A rotor assembly "
        "takes 18 flight hours to obtain and fit, so an alert with 6 hours of warning "
        "is a correct prediction and a grounded aircraft. Precision and recall cannot "
        "tell those two alerts apart - both are true positives."
    )

    threshold = st.select_slider(
        "Alarm threshold (multiple of the component's own vibration baseline)",
        options=sorted(sweep["VibThreshold"].unique()),
        value=min(sorted(sweep["VibThreshold"].unique()),
                  key=lambda v: abs(float(v) - pinned)),
    )

    at = sweep[sweep["VibThreshold"] == threshold]
    st.subheader(f"At a threshold of {float(threshold):.2f}x baseline")

    for _, row in at.sort_values("ComponentCode").iterrows():
        code = row["ComponentCode"]
        need = float(intervals.get(code, 0))
        c1, c2, c3, c4 = st.columns(4)
        c1.markdown(f"**{code}**  \npart lead time {need:.0f} flight hours")
        prec = float(row["PrecisionPct"]) if pd.notna(row["PrecisionPct"]) else 0.0
        act = float(row["ActionableLeadTimePct"]) if pd.notna(row["ActionableLeadTimePct"]) else 0.0
        med = float(row["MedianLeadTimeFlightHours"]) if pd.notna(row["MedianLeadTimeFlightHours"]) else 0.0
        metric_card(c2, "Precision", f"{prec:.2f}%", "Green" if prec >= 75 else "Red",
                    "Of the alerts raised, how many were right")
        metric_card(c3, "Actionable lead time", f"{act:.2f}%", "Green" if act >= 70 else "Red",
                    "Of the failures caught, how many in time to act")
        metric_card(c4, "Median warning", f"{med:.1f} h",
                    "Green" if med >= need else "Red",
                    f"against {need:.0f} h to obtain the part")

    st.subheader("The trade-off, across every threshold")
    st.markdown(
        "Precision rises with the threshold and lead time falls with it, "
        "**monotonically**. The conflict is structural, not a tuning mistake - "
        "which is why the fix is not 'tune it better'."
    )
    for code in sorted(sweep["ComponentCode"].unique()):
        part = sweep[sweep["ComponentCode"] == code].set_index("VibThreshold")
        st.caption(f"{code} - part lead time {intervals.get(code, 0):.0f} flight hours")
        st.line_chart(
            part[["PrecisionPct", "RecallPct", "ActionableLeadTimePct"]],
            height=240,
        )

    st.subheader("What to change")
    st.markdown(
        "The fleet runs **one threshold across two components** whose degradation "
        "curves have nothing in common. A rotor bearing's vibration rises gradually "
        "from about half its life; a motor controller's stays flat and then turns up "
        "sharply past 85%. At the setting that makes rotor precision acceptable, the "
        "motor-controller alarm becomes almost perfectly accurate and almost entirely "
        "useless.\n\n"
        "Pick a threshold per component, chosen on **actionable lead time subject to a "
        "precision floor** - not on precision, and not on F1. Run "
        "`EXEC dbo.usp_RecommendedThresholds` for the recommendation and the fleet "
        "effect of adopting it."
    )


# =============================================================================
# 5. DATA QUALITY
# =============================================================================
else:
    st.title("What is wrong with the data, and does the answer survive it?")
    findings = data_access.load("dq_findings")

    summary = (findings.groupby(["CheckCode", "CheckName", "Severity"])
                       .agg(Findings=("Detail", "size"),
                            AffectingToday=("AffectsCurrentWear", "sum"))
                       .reset_index()
                       .sort_values("CheckCode"))

    st.markdown(
        "Twelve behavioural checks run. **Seven of them found nothing and are reported "
        "anyway** - a summary listing only what was found cannot distinguish "
        "*we looked and it was clean* from *we never looked*."
    )
    st.dataframe(summary, width="stretch", hide_index=True)

    st.subheader("The gate")
    st.markdown(
        "The gate does not count defective rows. It asks what share of **flight-critical "
        "components fitted right now** would answer differently if the flagged data were "
        "corrected - comparing each component's uncertainty band against its margin to "
        "the threshold.\n\n"
        "A duplicated sortie from March 2024 is a real defect and completely irrelevant, "
        "because the component it inflated has been replaced twice since. Counting it "
        "would make a harmless problem look the same size as a real one."
    )

    st.subheader("Every finding")
    pick = st.multiselect("Check", sorted(findings["CheckCode"].unique()))
    view = findings[findings["CheckCode"].isin(pick)] if pick else findings
    st.dataframe(
        view[["CheckCode", "Severity", "EntityType", "EntityRef", "Detail", "AffectsCurrentWear"]],
        width="stretch", hide_index=True,
    )
