/*
================================================================================
Project 2 -- Vantage Wholesale Supply: Receivables Performance
Script:  01_create_schema.sql
Purpose: Creates the VantageAR database: a star schema for accounts
         receivable (invoices, cash receipts, credit memos / write-offs)
         plus the reference tables that drive every downstream threshold.

Business question:
   "Which accounts and terms are driving DSO up, and who should collections
    call first?"

DATA DISCLOSURE: Vantage Wholesale Supply is a fictional company. All data
loaded into this schema is synthetically generated by
02_generate_synthetic_data.sql. No confidential, proprietary, or production
data of any real organization is used or represented.
================================================================================
*/

IF DB_ID('VantageAR') IS NULL
    CREATE DATABASE VantageAR;
GO

USE VantageAR;
GO

-- Drop in dependency order so the script is safely re-runnable ---------------
IF OBJECT_ID('dbo.Fact_Adjustment', 'U')      IS NOT NULL DROP TABLE dbo.Fact_Adjustment;
IF OBJECT_ID('dbo.Fact_PromiseToPay', 'U')    IS NOT NULL DROP TABLE dbo.Fact_PromiseToPay;
IF OBJECT_ID('dbo.Fact_CashApplication', 'U') IS NOT NULL DROP TABLE dbo.Fact_CashApplication;
IF OBJECT_ID('dbo.Fact_CashReceipt', 'U')     IS NOT NULL DROP TABLE dbo.Fact_CashReceipt;
IF OBJECT_ID('dbo.Fact_Payment', 'U')         IS NOT NULL DROP TABLE dbo.Fact_Payment;
IF OBJECT_ID('dbo.Fact_Invoice', 'U')     IS NOT NULL DROP TABLE dbo.Fact_Invoice;
IF OBJECT_ID('dbo.Dim_Customer', 'U')     IS NOT NULL DROP TABLE dbo.Dim_Customer;
IF OBJECT_ID('dbo.Dim_Collector', 'U')    IS NOT NULL DROP TABLE dbo.Dim_Collector;
IF OBJECT_ID('dbo.Dim_PaymentTerms', 'U') IS NOT NULL DROP TABLE dbo.Dim_PaymentTerms;
IF OBJECT_ID('dbo.Dim_Date', 'U')         IS NOT NULL DROP TABLE dbo.Dim_Date;
IF OBJECT_ID('dbo.Ref_ARTargets', 'U')    IS NOT NULL DROP TABLE dbo.Ref_ARTargets;
IF OBJECT_ID('dbo.Ref_AgingBucket', 'U')  IS NOT NULL DROP TABLE dbo.Ref_AgingBucket;
GO

-- =============================================================================
-- DIMENSION: Dim_Date  (covers invoices, due dates and payments that land
-- after the 2025-12-31 reporting date)
-- =============================================================================
CREATE TABLE dbo.Dim_Date (
    DateKey      INT          NOT NULL PRIMARY KEY,   -- YYYYMMDD
    [Date]       DATE         NOT NULL UNIQUE,
    [Year]       SMALLINT     NOT NULL,
    [Quarter]    TINYINT      NOT NULL,
    [Month]      TINYINT      NOT NULL,
    MonthName    VARCHAR(10)  NOT NULL,
    YearMonth    CHAR(7)      NOT NULL,               -- 'YYYY-MM', sorts correctly as text
    MonthEndDate DATE         NOT NULL,
    IsMonthEnd   BIT          NOT NULL,
    IsWeekend    BIT          NOT NULL
);
GO

-- =============================================================================
-- DIMENSION: Dim_PaymentTerms
-- =============================================================================
CREATE TABLE dbo.Dim_PaymentTerms (
    TermsKey        INT IDENTITY(1,1) PRIMARY KEY,
    TermsCode       VARCHAR(12)  NOT NULL UNIQUE,     -- e.g. NET30, 2/10NET30
    TermsName       VARCHAR(40)  NOT NULL,
    NetDays         SMALLINT     NOT NULL CHECK (NetDays BETWEEN 0 AND 180),
    DiscountPct     DECIMAL(5,2) NOT NULL DEFAULT 0 CHECK (DiscountPct BETWEEN 0 AND 10),
    DiscountDays    SMALLINT     NOT NULL DEFAULT 0 CHECK (DiscountDays >= 0),
    CHECK (DiscountDays <= NetDays)
);
GO

-- =============================================================================
-- DIMENSION: Dim_Collector  (who owns the follow-up call)
-- =============================================================================
CREATE TABLE dbo.Dim_Collector (
    CollectorKey    INT IDENTITY(1,1) PRIMARY KEY,
    CollectorID     VARCHAR(10)  NOT NULL UNIQUE,
    CollectorName   VARCHAR(80)  NOT NULL,
    Team            VARCHAR(30)  NOT NULL CHECK (Team IN ('Strategic Accounts','Commercial','Small Business'))
);
GO

-- =============================================================================
-- DIMENSION: Dim_Customer
-- CurrentTermsKey is the customer's terms TODAY. Each invoice carries the
-- terms that applied when it was raised (Fact_Invoice.TermsKey), because
-- terms changed mid-period for some customers -- that history is part of
-- the DSO story, so it must not be overwritten.
-- =============================================================================
CREATE TABLE dbo.Dim_Customer (
    CustomerKey      INT IDENTITY(1,1) PRIMARY KEY,
    CustomerID       VARCHAR(10)   NOT NULL UNIQUE,
    CustomerName     VARCHAR(100)  NOT NULL,
    Segment          VARCHAR(30)   NOT NULL CHECK (Segment IN ('Contractor','OEM Manufacturer','MRO Reseller','Institutional')),
    Region           VARCHAR(20)   NOT NULL CHECK (Region IN ('Northeast','Southeast','Midwest','Southwest','West')),
    SalesRep         VARCHAR(80)   NOT NULL,
    CollectorKey     INT           NOT NULL REFERENCES dbo.Dim_Collector(CollectorKey),
    CurrentTermsKey  INT           NOT NULL REFERENCES dbo.Dim_PaymentTerms(TermsKey),
    CreditLimit      DECIMAL(12,2) NOT NULL CHECK (CreditLimit > 0),
    RiskTier         VARCHAR(10)   NOT NULL CHECK (RiskTier IN ('Low','Medium','High')),
    CustomerSince    DATE          NOT NULL
);
GO

-- =============================================================================
-- FACT: Fact_Invoice  (grain: one row per invoice)
-- =============================================================================
CREATE TABLE dbo.Fact_Invoice (
    InvoiceKey       BIGINT IDENTITY(1,1) PRIMARY KEY,
    InvoiceNo        VARCHAR(15)   NOT NULL UNIQUE,
    CustomerKey      INT           NOT NULL REFERENCES dbo.Dim_Customer(CustomerKey),
    TermsKey         INT           NOT NULL REFERENCES dbo.Dim_PaymentTerms(TermsKey),
    ShipDateKey      INT           NULL     REFERENCES dbo.Dim_Date(DateKey),
    InvoiceDateKey   INT           NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    DueDateKey       INT           NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    InvoiceAmount    DECIMAL(12,2) NOT NULL CHECK (InvoiceAmount > 0),
    IsDisputed       BIT           NOT NULL DEFAULT 0,
    DisputeReason    VARCHAR(40)   NULL CHECK (DisputeReason IS NULL OR DisputeReason IN ('Pricing','Short Shipment','Damaged Goods','Duplicate Billing','PO Mismatch')),
    DisputeOpenedKey INT           NULL REFERENCES dbo.Dim_Date(DateKey),
    DisputeClosedKey INT           NULL REFERENCES dbo.Dim_Date(DateKey),
    CHECK (DueDateKey >= InvoiceDateKey),
    CHECK ((IsDisputed = 0 AND DisputeReason IS NULL) OR (IsDisputed = 1 AND DisputeReason IS NOT NULL))
);
GO

CREATE INDEX IX_FactInvoice_Customer    ON dbo.Fact_Invoice(CustomerKey);
CREATE INDEX IX_FactInvoice_InvoiceDate ON dbo.Fact_Invoice(InvoiceDateKey);
CREATE INDEX IX_FactInvoice_DueDate     ON dbo.Fact_Invoice(DueDateKey);
GO

-- =============================================================================
-- FACT: Fact_CashReceipt  (grain: one cash receipt as it hits the bank)
--
-- WHY THE RECEIPT IS SEPARATE FROM WHAT IT PAYS
--   One cheque routinely settles a dozen invoices, and cash frequently arrives
--   with no remittance advice saying which. Holding the receipt and its
--   application in a single row makes two different questions collapse into
--   one: "is this invoice open?" and "does this customer owe us money?" are not
--   the same question, and the difference between them is unapplied cash --
--   money already in the bank that nobody has matched to an invoice.
--
--   With a single table, an account that has paid still looks unpaid, and the
--   collections queue sends someone to chase it. That is the single most
--   damaging call a collections team can make.
--
--   RemittanceAdviceReceived records whether the customer told us what the
--   money was for. It is the usual root cause of a receipt sitting unapplied.
-- =============================================================================
CREATE TABLE dbo.Fact_CashReceipt (
    ReceiptKey       BIGINT IDENTITY(1,1) PRIMARY KEY,
    ReceiptNo        VARCHAR(15)   NOT NULL UNIQUE,
    CustomerKey      INT           NOT NULL REFERENCES dbo.Dim_Customer(CustomerKey),
    ReceiptDateKey   INT           NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    ReceiptAmount    DECIMAL(12,2) NOT NULL CHECK (ReceiptAmount > 0),
    PaymentMethod    VARCHAR(10)   NOT NULL CHECK (PaymentMethod IN ('ACH','Wire','Check','Card')),
    RemittanceAdviceReceived BIT   NOT NULL DEFAULT 1,
    BankBatchID      VARCHAR(20)   NOT NULL
);
GO

CREATE INDEX IX_FactCashReceipt_Customer ON dbo.Fact_CashReceipt(CustomerKey);
CREATE INDEX IX_FactCashReceipt_Date     ON dbo.Fact_CashReceipt(ReceiptDateKey);
GO

-- =============================================================================
-- FACT: Fact_CashApplication  (grain: one receipt applied to one invoice)
--
-- WHY ApplicationDateKey EXISTS SEPARATELY FROM THE RECEIPT DATE
--   The date that reduces an invoice balance is the date the cash was APPLIED,
--   not the date it landed in the bank. Cash banked on 28 December and applied
--   on 4 January does not cure a December ageing bucket, and treating it as if
--   it did is a well-worn way to flatter a month end. Both dates are kept so
--   the lag between them is measurable rather than assumed away.
--
--   An invoice may be settled by several applications (instalments, or several
--   cheques), and one receipt may spread across many invoices. Hence a separate
--   fact rather than a column on either side.
-- =============================================================================
CREATE TABLE dbo.Fact_CashApplication (
    ApplicationKey     BIGINT IDENTITY(1,1) PRIMARY KEY,
    ReceiptKey         BIGINT        NOT NULL REFERENCES dbo.Fact_CashReceipt(ReceiptKey),
    InvoiceKey         BIGINT        NOT NULL REFERENCES dbo.Fact_Invoice(InvoiceKey),
    CustomerKey        INT           NOT NULL REFERENCES dbo.Dim_Customer(CustomerKey),
    ApplicationDateKey INT           NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    AppliedAmount      DECIMAL(12,2) NOT NULL CHECK (AppliedAmount > 0),
    DiscountTaken      DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (DiscountTaken >= 0)
);
GO

CREATE INDEX IX_FactCashApp_Invoice ON dbo.Fact_CashApplication(InvoiceKey);
CREATE INDEX IX_FactCashApp_Receipt ON dbo.Fact_CashApplication(ReceiptKey);
CREATE INDEX IX_FactCashApp_Date    ON dbo.Fact_CashApplication(ApplicationDateKey);
GO

-- =============================================================================
-- FACT: Fact_PromiseToPay  (grain: one promise obtained on one call)
--
-- WHY THERE IS NO Status COLUMN
--   A promise is logged by the collector who obtained it -- the same person the
--   kept-rate is measuring. If the outcome were a stored column, the metric
--   would be self-reported by the party being scored, and a collector under
--   pressure would log optimistic promises and generous outcomes.
--
--   Status is therefore derived from cash actually applied, in
--   dbo.fn_PromiseStatus, and can only be changed by a customer paying.
--   The register records what was promised; the bank records what happened.
-- =============================================================================
CREATE TABLE dbo.Fact_PromiseToPay (
    PromiseKey         BIGINT IDENTITY(1,1) PRIMARY KEY,
    PromiseNo          VARCHAR(15)   NOT NULL UNIQUE,
    CustomerKey        INT           NOT NULL REFERENCES dbo.Dim_Customer(CustomerKey),
    CollectorKey       INT           NOT NULL REFERENCES dbo.Dim_Collector(CollectorKey),
    PromiseMadeKey     INT           NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    PromisedPayDateKey INT           NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    PromisedAmount     DECIMAL(12,2) NOT NULL CHECK (PromisedAmount > 0),
    CHECK (PromisedPayDateKey >= PromiseMadeKey)
);
GO

CREATE INDEX IX_FactPromise_Customer ON dbo.Fact_PromiseToPay(CustomerKey);
CREATE INDEX IX_FactPromise_DueDate  ON dbo.Fact_PromiseToPay(PromisedPayDateKey);
GO

-- =============================================================================
-- FACT: Fact_Adjustment  (credit memos and bad-debt write-offs)
-- =============================================================================
CREATE TABLE dbo.Fact_Adjustment (
    AdjustmentKey    BIGINT IDENTITY(1,1) PRIMARY KEY,
    AdjustmentNo     VARCHAR(15)   NOT NULL UNIQUE,
    InvoiceKey       BIGINT        NOT NULL REFERENCES dbo.Fact_Invoice(InvoiceKey),
    CustomerKey      INT           NOT NULL REFERENCES dbo.Dim_Customer(CustomerKey),
    AdjustmentDateKey INT          NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    AdjustmentType   VARCHAR(12)   NOT NULL CHECK (AdjustmentType IN ('CreditMemo','WriteOff')),
    Amount           DECIMAL(12,2) NOT NULL CHECK (Amount > 0),
    Reason           VARCHAR(40)   NOT NULL
);
GO

-- =============================================================================
-- REFERENCE: Ref_AgingBucket  (one definition of the buckets, used by SQL,
-- Power Query and the Excel formulas alike)
-- =============================================================================
CREATE TABLE dbo.Ref_AgingBucket (
    BucketKey     TINYINT     NOT NULL PRIMARY KEY,
    BucketName    VARCHAR(12) NOT NULL UNIQUE,
    MinDaysPastDue SMALLINT   NOT NULL,       -- inclusive; negative = not yet due
    MaxDaysPastDue SMALLINT   NOT NULL,       -- inclusive
    RiskWeight    DECIMAL(4,2) NOT NULL       -- used by the collections priority score
);
GO

INSERT INTO dbo.Ref_AgingBucket (BucketKey, BucketName, MinDaysPastDue, MaxDaysPastDue, RiskWeight) VALUES
(1, 'Current',  -9999,     0, 0.00),
(2, '1-30',         1,    30, 0.25),
(3, '31-60',       31,    60, 0.50),
(4, '61-90',       61,    90, 0.75),
(5, '90+',         91,  9999, 1.00);
GO

-- =============================================================================
-- REFERENCE: Ref_ARTargets  (single source of truth for every threshold)
-- =============================================================================
CREATE TABLE dbo.Ref_ARTargets (
    MetricName    VARCHAR(40)   NOT NULL PRIMARY KEY,
    TargetValue   DECIMAL(10,2) NOT NULL,
    WarningValue  DECIMAL(10,2) NOT NULL,
    Direction     VARCHAR(15)   NOT NULL CHECK (Direction IN ('HigherBetter','LowerBetter')),
    Unit          VARCHAR(10)   NOT NULL CHECK (Unit IN ('Days','Percent','Currency')),
    Description   VARCHAR(200)  NOT NULL
);
GO

INSERT INTO dbo.Ref_ARTargets (MetricName, TargetValue, WarningValue, Direction, Unit, Description) VALUES
('DSO',                 45.00,   55.00, 'LowerBetter',  'Days',     'Days Sales Outstanding (countback method) at month end'),
('AvgDaysDelinquent',    8.00,   15.00, 'LowerBetter',  'Days',     'DSO minus Best Possible DSO: days lost to late payment'),
('CEI',                 85.00,   75.00, 'HigherBetter', 'Percent',  'Collection Effectiveness Index for the month'),
('PctPastDue',          15.00,   25.00, 'LowerBetter',  'Percent',  'Share of open AR balance that is past due'),
('Pct90Plus',            3.00,    6.00, 'LowerBetter',  'Percent',  'Share of open AR balance more than 90 days past due'),
('CreditUtilization',   80.00,  100.00, 'LowerBetter',  'Percent',  'Customer open balance as a share of credit limit'),
('DisputeAgeDays',      15.00,   30.00, 'LowerBetter',  'Days',     'Age of an unresolved dispute before it must be escalated'),
('UnappliedCashPct',     0.50,    1.50, 'LowerBetter',  'Percent',  'Cash received but not matched to an invoice, as a share of open AR'),
('BillingLagDays',       2.00,    4.00, 'LowerBetter',  'Days',     'Dollar-weighted days between shipping goods and issuing the invoice'),
('PromiseKeptRate',     80.00,   65.00, 'HigherBetter', 'Percent',  'Share of promised dollars actually received within the grace window');
GO

PRINT 'VantageAR schema created: 4 dimensions, 5 facts, 2 reference tables.';
GO
