/*
================================================================================
Project 3 -- Lumen Optics Manufacturing: Photonics Spend Scorecard
Script:  01_create_schema.sql
Purpose: Creates the LumenSpend database -- a star schema for direct-materials
         procurement in a photonics manufacturer, plus the reference tables
         that drive every downstream threshold and assumption.

Business question:
   "Our purchase prices are flat or falling and every variance report is green
    -- so why is material cost per ACCEPTED unit rising, and which
    supplier-part combinations should sourcing renegotiate first?"

THREE MODELLING DECISIONS WORTH STATING UP FRONT

  1. A PRICE AGREEMENT IS A FACT, NOT AN ATTRIBUTE.
     A contracted price is true between two dates and false outside them.
     Storing it as a column on the part or the vendor would make today's
     contract retroactively govern a purchase made two years ago, so every
     historical price variance would be measured against a price that did not
     exist at the time. Fact_PriceAgreement is therefore dated, and purchase
     price variance joins on the agreement in force at the ORDER date.

  2. RECEIPTS CARRY ACCEPTANCE, NOT JUST QUANTITY.
     In optics a component can arrive, be counted, and still be unusable --
     surface figure out of spec, coating defects, fibre attenuation above
     tolerance. If a receipt records only quantity, then the cheapest supplier
     by unit price always wins, because the cost of what they shipped that
     could not be used is invisible. Splitting QtyAccepted from QtyRejected is
     what makes cost per ACCEPTED unit computable.

  3. EXPECTED PRICE EROSION IS A REFERENCE TABLE, NOT A CONSTANT IN A QUERY.
     Photonic components follow learning curves: unit prices decline as
     volumes rise and processes mature. That expectation is an ASSUMPTION, it
     varies by category, and it is the single most contestable input in this
     analysis -- so it lives in Ref_PriceErosionBenchmark where a category
     manager can see it, challenge it and change it, rather than buried in a
     CASE expression where nobody will ever find it.

DATA DISCLOSURE: Lumen Optics Manufacturing is a fictional company. All data
loaded into this schema is synthetically generated by
02_generate_synthetic_data.sql. No confidential, proprietary, or production
data of any real organization is used or represented.
================================================================================
*/

IF DB_ID('LumenSpend') IS NULL
    CREATE DATABASE LumenSpend;
GO

USE LumenSpend;
GO

-- Drop in dependency order so the script is safely re-runnable ---------------
IF OBJECT_ID('dbo.Fact_GoodsReceipt', 'U')    IS NOT NULL DROP TABLE dbo.Fact_GoodsReceipt;
IF OBJECT_ID('dbo.Fact_PurchaseOrderLine','U')IS NOT NULL DROP TABLE dbo.Fact_PurchaseOrderLine;
IF OBJECT_ID('dbo.Fact_PriceAgreement', 'U')  IS NOT NULL DROP TABLE dbo.Fact_PriceAgreement;
IF OBJECT_ID('dbo.Dim_Part', 'U')             IS NOT NULL DROP TABLE dbo.Dim_Part;
IF OBJECT_ID('dbo.Dim_Vendor', 'U')           IS NOT NULL DROP TABLE dbo.Dim_Vendor;
IF OBJECT_ID('dbo.Dim_Buyer', 'U')            IS NOT NULL DROP TABLE dbo.Dim_Buyer;
IF OBJECT_ID('dbo.Dim_Date', 'U')             IS NOT NULL DROP TABLE dbo.Dim_Date;
IF OBJECT_ID('dbo.Ref_PriceErosionBenchmark','U') IS NOT NULL DROP TABLE dbo.Ref_PriceErosionBenchmark;
IF OBJECT_ID('dbo.Ref_RejectReason', 'U')     IS NOT NULL DROP TABLE dbo.Ref_RejectReason;
IF OBJECT_ID('dbo.Ref_SpendTargets', 'U')     IS NOT NULL DROP TABLE dbo.Ref_SpendTargets;
GO

-- =============================================================================
-- DIMENSION: Dim_Date
-- Covers order dates, promised dates, receipt dates and agreement validity.
-- =============================================================================
CREATE TABLE dbo.Dim_Date (
    DateKey      INT          NOT NULL PRIMARY KEY,   -- YYYYMMDD
    [Date]       DATE         NOT NULL UNIQUE,
    [Year]       SMALLINT     NOT NULL,
    [Quarter]    TINYINT      NOT NULL,
    [Month]      TINYINT      NOT NULL,
    MonthName    VARCHAR(12)  NOT NULL,
    YearMonth    CHAR(7)      NOT NULL,
    YearQuarter  CHAR(7)      NOT NULL,
    MonthEndDate DATE         NOT NULL,
    IsMonthEnd   BIT          NOT NULL,
    IsWeekend    BIT          NOT NULL
);
GO
CREATE INDEX IX_DimDate_Date      ON dbo.Dim_Date([Date]);
CREATE INDEX IX_DimDate_YearMonth ON dbo.Dim_Date(YearMonth);
GO

-- =============================================================================
-- DIMENSION: Dim_Buyer  (the sourcing team; a category manager owns categories)
-- =============================================================================
CREATE TABLE dbo.Dim_Buyer (
    BuyerKey     INT IDENTITY(1,1) PRIMARY KEY,
    BuyerID      VARCHAR(10)  NOT NULL UNIQUE,
    BuyerName    VARCHAR(60)  NOT NULL,
    Team         VARCHAR(30)  NOT NULL,
    IsActive     BIT          NOT NULL DEFAULT 1
);
GO

-- =============================================================================
-- DIMENSION: Dim_Vendor
--
-- RelationshipStartDate exists because leverage is partly a function of history:
-- a supplier three months into a first contract negotiates differently from one
-- eight years in. LumenRevenueSharePct is our estimate of how much of THEIR
-- revenue we represent -- the single most useful leverage signal in sourcing,
-- and the reason a large spend with a huge supplier can carry less weight than
-- a small spend with a small one.
-- =============================================================================
CREATE TABLE dbo.Dim_Vendor (
    VendorKey            INT IDENTITY(1,1) PRIMARY KEY,
    VendorID             VARCHAR(10)   NOT NULL UNIQUE,
    VendorName           VARCHAR(80)   NOT NULL,
    Country              VARCHAR(30)   NOT NULL,
    VendorTier           VARCHAR(15)   NOT NULL CHECK (VendorTier IN ('Strategic','Preferred','Approved','Transactional')),
    RelationshipStartDate DATE         NOT NULL,
    LumenRevenueSharePct DECIMAL(5,2)  NOT NULL CHECK (LumenRevenueSharePct BETWEEN 0 AND 100),
    IsActive             BIT           NOT NULL DEFAULT 1
);
GO
CREATE INDEX IX_DimVendor_Tier ON dbo.Dim_Vendor(VendorTier);
GO

-- =============================================================================
-- DIMENSION: Dim_Part
--
-- QualificationMonths and QualifiedSupplierCount together decide whether
-- sourcing has any leverage at all. A sole-source photonic component with a
-- nine-month requalification cannot be renegotiated by threatening to leave --
-- there is nowhere to go inside the planning horizon. Recording both stops the
-- priority queue from recommending a negotiation that cannot be won, which is
-- the fastest way to lose a sourcing team's trust in a report.
-- =============================================================================
CREATE TABLE dbo.Dim_Part (
    PartKey                 INT IDENTITY(1,1) PRIMARY KEY,
    PartNumber              VARCHAR(20)  NOT NULL UNIQUE,
    PartName                VARCHAR(80)  NOT NULL,
    Category                VARCHAR(30)  NOT NULL CHECK (Category IN
                              ('Laser Diode','Photodetector','Optical Fibre','Lens Assembly',
                               'Optical Coating','Precision Mount','Fibre Connector','Thermal Control')),
    UnitOfMeasure           VARCHAR(10)  NOT NULL,
    Criticality             VARCHAR(10)  NOT NULL CHECK (Criticality IN ('Critical','Standard','Commodity')),
    QualifiedSupplierCount  TINYINT      NOT NULL CHECK (QualifiedSupplierCount >= 1),
    QualificationMonths     TINYINT      NOT NULL CHECK (QualificationMonths >= 0),
    FirstPurchaseDate       DATE         NOT NULL
);
GO
CREATE INDEX IX_DimPart_Category ON dbo.Dim_Part(Category);
GO

-- =============================================================================
-- FACT: Fact_PriceAgreement  (grain: one negotiated price for one part from one
-- vendor, valid between two dates)
--
-- Dated on purpose -- see modelling decision 1 in the header. ValidToDateKey is
-- NULL for an open-ended agreement, and the lookup must treat NULL as "still in
-- force" rather than excluding it, which is the usual way a dated-join bug
-- makes contract coverage look far worse than it is.
-- =============================================================================
CREATE TABLE dbo.Fact_PriceAgreement (
    AgreementKey     INT IDENTITY(1,1) PRIMARY KEY,
    AgreementNo      VARCHAR(15)   NOT NULL UNIQUE,
    VendorKey        INT           NOT NULL REFERENCES dbo.Dim_Vendor(VendorKey),
    PartKey          INT           NOT NULL REFERENCES dbo.Dim_Part(PartKey),
    ValidFromDateKey INT           NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    ValidToDateKey   INT           NULL     REFERENCES dbo.Dim_Date(DateKey),
    AgreedUnitPrice  DECIMAL(12,4) NOT NULL CHECK (AgreedUnitPrice > 0),
    MinOrderQty      INT           NOT NULL DEFAULT 1,
    CHECK (ValidToDateKey IS NULL OR ValidToDateKey >= ValidFromDateKey)
);
GO
CREATE INDEX IX_Agreement_PartVendor ON dbo.Fact_PriceAgreement(PartKey, VendorKey);
GO

-- =============================================================================
-- FACT: Fact_PurchaseOrderLine  (grain: one line on one purchase order)
--
-- Freight and expedite are held per LINE, not netted into the unit price,
-- because they answer different questions and have different owners. A unit
-- price is negotiated with the supplier; an expedite fee is caused by planning.
-- Folding them together hides which of the two is costing the money, and it is
-- usually the one nobody is looking at.
-- =============================================================================
CREATE TABLE dbo.Fact_PurchaseOrderLine (
    POLineKey        BIGINT IDENTITY(1,1) PRIMARY KEY,
    PONumber         VARCHAR(15)   NOT NULL,
    POLineNo         SMALLINT      NOT NULL,
    PartKey          INT           NOT NULL REFERENCES dbo.Dim_Part(PartKey),
    VendorKey        INT           NOT NULL REFERENCES dbo.Dim_Vendor(VendorKey),
    BuyerKey         INT           NOT NULL REFERENCES dbo.Dim_Buyer(BuyerKey),
    OrderDateKey     INT           NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    PromisedDateKey  INT           NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    OrderQty         INT           NOT NULL CHECK (OrderQty > 0),
    UnitPrice        DECIMAL(12,4) NOT NULL CHECK (UnitPrice > 0),
    FreightAmount    DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (FreightAmount >= 0),
    ExpediteFee      DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (ExpediteFee >= 0),
    IsExpedited      BIT           NOT NULL DEFAULT 0,
    CONSTRAINT UQ_POLine UNIQUE (PONumber, POLineNo),
    CHECK (PromisedDateKey >= OrderDateKey),
    -- an expedite fee without the flag, or the flag without a fee, is a data
    -- defect the quality layer looks for; the constraint permits neither
    CHECK ((IsExpedited = 1 AND ExpediteFee > 0) OR (IsExpedited = 0 AND ExpediteFee = 0))
);
GO
CREATE INDEX IX_POLine_Part      ON dbo.Fact_PurchaseOrderLine(PartKey);
CREATE INDEX IX_POLine_Vendor    ON dbo.Fact_PurchaseOrderLine(VendorKey);
CREATE INDEX IX_POLine_OrderDate ON dbo.Fact_PurchaseOrderLine(OrderDateKey);
GO

-- =============================================================================
-- FACT: Fact_GoodsReceipt  (grain: one receipt against one purchase order line)
--
-- A line may be received in several deliveries, so this is not one-to-one with
-- the order line. QtyAccepted + QtyRejected = QtyReceived is enforced here
-- rather than assumed downstream: a receipt whose parts do not add up makes
-- every yield figure wrong in a way no totals check would notice.
-- =============================================================================
CREATE TABLE dbo.Fact_GoodsReceipt (
    ReceiptKey       BIGINT IDENTITY(1,1) PRIMARY KEY,
    ReceiptNo        VARCHAR(15)   NOT NULL UNIQUE,
    POLineKey        BIGINT        NOT NULL REFERENCES dbo.Fact_PurchaseOrderLine(POLineKey),
    ReceiptDateKey   INT           NOT NULL REFERENCES dbo.Dim_Date(DateKey),
    QtyReceived      INT           NOT NULL CHECK (QtyReceived > 0),
    QtyAccepted      INT           NOT NULL CHECK (QtyAccepted >= 0),
    QtyRejected      INT           NOT NULL CHECK (QtyRejected >= 0),
    RejectReasonCode VARCHAR(20)   NULL,
    CHECK (QtyAccepted + QtyRejected = QtyReceived),
    CHECK ((QtyRejected = 0 AND RejectReasonCode IS NULL)
        OR (QtyRejected > 0 AND RejectReasonCode IS NOT NULL))
);
GO
CREATE INDEX IX_Receipt_POLine ON dbo.Fact_GoodsReceipt(POLineKey);
CREATE INDEX IX_Receipt_Date   ON dbo.Fact_GoodsReceipt(ReceiptDateKey);
GO

-- =============================================================================
-- REFERENCE: Ref_RejectReason
-- Photonics-specific failure modes. Grouped by whether the cause sits with the
-- supplier or with us, because only the first is negotiable.
-- =============================================================================
CREATE TABLE dbo.Ref_RejectReason (
    RejectReasonCode VARCHAR(20) NOT NULL PRIMARY KEY,
    Description      VARCHAR(80) NOT NULL,
    Attribution      VARCHAR(12) NOT NULL CHECK (Attribution IN ('Supplier','Lumen','Shared'))
);
GO

INSERT INTO dbo.Ref_RejectReason (RejectReasonCode, Description, Attribution) VALUES
('SURFACE_FIGURE',  'Surface figure outside specified wavefront tolerance',      'Supplier'),
('COATING_DEFECT',  'Coating pinholes, delamination or non-uniform reflectance', 'Supplier'),
('ATTENUATION',     'Fibre attenuation above specified dB/km',                   'Supplier'),
('BEAM_PROFILE',    'Laser beam profile or divergence out of specification',     'Supplier'),
('DIMENSIONAL',     'Mechanical dimensions outside drawing tolerance',           'Supplier'),
('CONTAMINATION',   'Particulate or hydrocarbon contamination on optical face',  'Shared'),
('TRANSIT_DAMAGE',  'Damage consistent with handling or packaging in transit',   'Shared'),
('SPEC_CHANGE',     'Rejected against a drawing revision issued after the order','Lumen');
GO

-- =============================================================================
-- REFERENCE: Ref_PriceErosionBenchmark
--
-- The most contestable input in the whole project, so it is visible and
-- editable rather than hidden in a query -- see modelling decision 3.
--
-- Photonic components follow learning curves: as cumulative volume rises and
-- processes mature, unit cost falls. A supplier holding price FLAT across three
-- years of a declining category is extracting margin quietly, and no variance
-- report catches it because the price never went up.
--
-- SourceNote records where each figure came from, because an assumption without
-- a provenance is an opinion, and the first question a category manager will
-- ask is "says who?".
-- =============================================================================
CREATE TABLE dbo.Ref_PriceErosionBenchmark (
    Category               VARCHAR(30)  NOT NULL PRIMARY KEY,
    AnnualErosionPct       DECIMAL(5,2) NOT NULL,
    ToleranceBandPct       DECIMAL(5,2) NOT NULL,
    MaturityProfile        VARCHAR(12)  NOT NULL CHECK (MaturityProfile IN ('Emerging','Maturing','Mature')),
    SourceNote             VARCHAR(160) NOT NULL
);
GO

INSERT INTO dbo.Ref_PriceErosionBenchmark
    (Category, AnnualErosionPct, ToleranceBandPct, MaturityProfile, SourceNote) VALUES
('Laser Diode',     8.00, 2.00, 'Maturing', 'Illustrative learning-curve rate for volume telecom-grade emitters; replace with the category team''s own index.'),
('Photodetector',   6.50, 2.00, 'Maturing', 'Illustrative; detector pricing tracks wafer yield improvement.'),
('Optical Fibre',   4.00, 1.50, 'Mature',   'Illustrative; commodity fibre, thin margins, little room left to erode.'),
('Lens Assembly',   3.00, 1.50, 'Mature',   'Illustrative; precision grinding and polishing is labour-bound, so erosion is slow.'),
('Optical Coating', 5.00, 2.00, 'Maturing', 'Illustrative; coating runs benefit from chamber utilisation as volume rises.'),
('Precision Mount', 2.00, 1.50, 'Mature',   'Illustrative; machined metal tracks input cost more than learning.'),
('Fibre Connector', 7.00, 2.00, 'Maturing', 'Illustrative; high-volume moulded components erode quickly.'),
('Thermal Control', 5.50, 2.00, 'Maturing', 'Illustrative; TEC and driver electronics follow semiconductor curves.');
GO

-- =============================================================================
-- REFERENCE: Ref_SpendTargets  (single source of truth for every threshold,
-- read by SQL, by the DAX measures and by the Excel formulas alike)
-- =============================================================================
CREATE TABLE dbo.Ref_SpendTargets (
    MetricName    VARCHAR(40)   NOT NULL PRIMARY KEY,
    TargetValue   DECIMAL(10,2) NOT NULL,
    WarningValue  DECIMAL(10,2) NOT NULL,
    Direction     VARCHAR(15)   NOT NULL CHECK (Direction IN ('HigherBetter','LowerBetter')),
    Unit          VARCHAR(10)   NOT NULL CHECK (Unit IN ('Days','Percent','Currency','Index')),
    Description   VARCHAR(200)  NOT NULL
);
GO

INSERT INTO dbo.Ref_SpendTargets (MetricName, TargetValue, WarningValue, Direction, Unit, Description) VALUES
('PPVPct',              0.00,    2.00, 'LowerBetter',  'Percent',  'Purchase price variance against the agreement in force, as a share of contracted spend'),
('MaverickSpendPct',    5.00,   12.00, 'LowerBetter',  'Percent',  'Share of spend placed with no price agreement in force at the order date'),
('ErosionCapturePct',  80.00,   60.00, 'HigherBetter', 'Percent',  'Share of the expected category price erosion actually realised in paid prices'),
('AcceptanceRatePct',  98.00,   95.00, 'HigherBetter', 'Percent',  'Units accepted at incoming inspection as a share of units received'),
('OnTimeDeliveryPct',  95.00,   90.00, 'HigherBetter', 'Percent',  'Receipts on or before the promised date'),
('ExpediteSpendPct',    1.00,    3.00, 'LowerBetter',  'Percent',  'Expedite fees as a share of total material spend'),
('SingleSourceSpendPct',20.00,  35.00, 'LowerBetter',  'Percent',  'Share of spend on parts with only one qualified supplier'),
('Top5VendorSharePct',  50.00,   70.00, 'LowerBetter',  'Percent',  'Share of total spend held by the five largest vendors');
GO

DECLARE @missing VARCHAR(400) = '';
IF OBJECT_ID('dbo.Dim_Date', 'U')                  IS NULL SET @missing += 'Dim_Date ';
IF OBJECT_ID('dbo.Dim_Buyer', 'U')                 IS NULL SET @missing += 'Dim_Buyer ';
IF OBJECT_ID('dbo.Dim_Vendor', 'U')                IS NULL SET @missing += 'Dim_Vendor ';
IF OBJECT_ID('dbo.Dim_Part', 'U')                  IS NULL SET @missing += 'Dim_Part ';
IF OBJECT_ID('dbo.Fact_PriceAgreement', 'U')       IS NULL SET @missing += 'Fact_PriceAgreement ';
IF OBJECT_ID('dbo.Fact_PurchaseOrderLine', 'U')    IS NULL SET @missing += 'Fact_PurchaseOrderLine ';
IF OBJECT_ID('dbo.Fact_GoodsReceipt', 'U')         IS NULL SET @missing += 'Fact_GoodsReceipt ';
IF OBJECT_ID('dbo.Ref_RejectReason', 'U')          IS NULL SET @missing += 'Ref_RejectReason ';
IF OBJECT_ID('dbo.Ref_PriceErosionBenchmark', 'U') IS NULL SET @missing += 'Ref_PriceErosionBenchmark ';
IF OBJECT_ID('dbo.Ref_SpendTargets', 'U')          IS NULL SET @missing += 'Ref_SpendTargets ';
IF @missing <> '' THROW 51001, 'FAILED to create schema objects -- scroll up for the error.', 1;
PRINT 'LumenSpend schema created: 4 dimensions, 3 facts, 3 reference tables.';
GO
